from voxelity_pro.enums.voxelity_enum import VoxelityEnum
from voxelity_pro.utils.utils import Utils

class NameConstant(VoxelityEnum):
    VOXILITY_VERSION_SUFFIX = Utils.get_gn_voxelizer_version() + "_" + Utils.get_addon_version(separator='_')
    VOXILITY_NAME="Voxelity"

    VOXILITY_NODE_GROUP_NAME_PREFIX = "VoxelityVoxelize_"
    VOXILITY_NODE_GROUP_NAME = VOXILITY_NODE_GROUP_NAME_PREFIX + VOXILITY_VERSION_SUFFIX
    VOXILITY_MODIFIER_NAME_PREFIX = "VoxelityVoxelizeModifier_"
    VOXILITY_MODIFIER_NAME = VOXILITY_MODIFIER_NAME_PREFIX + VOXILITY_VERSION_SUFFIX

    VOXILITY_EXTENDED_NODE_GROUP_PREFIX = "VoxelityNodeGroup_"
    VOXILITY_NODE_GROUP_CONSTRAIN_INPUT_PREFIX = VOXILITY_EXTENDED_NODE_GROUP_PREFIX + "ConstrainInput_"
    VOXILITY_NODE_GROUP_CONSTRAIN_INPUT = VOXILITY_NODE_GROUP_CONSTRAIN_INPUT_PREFIX + VOXILITY_VERSION_SUFFIX