#!/bin/bash

MENUS_DIR="menus/"
VOX_FORMATS_MENU_TEMPLATE="voxel_formats_menu.py.template.txt"
VOX_FORMATS_MENU_FILE="voxel_formats_menu.py"
VOX_OPERATORS_DIR="operators/voxel/"
VOX_OPERATOR_TEMPLATE="operator_{type}_exporter.template.txt"
FORMATS_FILE="supported-voxel-formats.txt"
TAB="    "

declare -A formats

process_voxel_format() {
    line=$1
    type=$(echo "$line" | awk -F ': ' '{print $1}')
    name=$(echo "$line" | awk -F ': ' '{$1=""; print $0}' | sed 's/^[[:space:]]*//')
    formats["$type"]=$name
}

read_and_process_voxel_formats() {
    while IFS= read -r line; do
        line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        if [ -z "$line" ]; then
            break
        fi
        process_voxel_format "$line"
    done < "${VOX_OPERATORS_DIR}${FORMATS_FILE}"
}

get_usage_text() {
    echo "Usage: $0 [-a|--all] | <type> <name>"
}

get_code_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '_'
}

get_autogenerate_notice() {
    echo "This file was autogenerated and should not be edited manually. Generated by script $0"
}

copy_and_modify_template() {
    local type="$1"
    local name="$2"

    code_name=$(get_code_name "$name")
    source_file="${VOX_OPERATORS_DIR}${VOX_OPERATOR_TEMPLATE}"
    destination_file="${VOX_OPERATORS_DIR}operator_${type}_exporter.py"

    cp "$source_file" "$destination_file"

    sed -i "1i # $(get_autogenerate_notice)" "$destination_file"
    sed -i "s/{{type}}/$type/g; s/{{name}}/$name/g; s/{{code_name}}/$code_name/g" "$destination_file"

    #echo "${TAB}bpy.utils.register_class(EXPORT_OT_$code_name)"
    #echo "from vox_exporter.operators.voxel.operator_${type}_exporter import EXPORT_OT_$code_name"
    echo "Generated operator .$type exporter file: $destination_file"
}

generate_voxel_formats_menu_py_file() {
    template_file="${MENUS_DIR}${VOX_FORMATS_MENU_TEMPLATE}"
    output_file="${MENUS_DIR}${VOX_FORMATS_MENU_FILE}"

    imports_content=""
    classes_content=""

    cp "$template_file" "$output_file"

    for type in "${!formats[@]}"; do
        if [ "$type" == "vox" ]; then
            continue
        fi
        name="${formats[$type]}"
        code_name=$(get_code_name "$name")

        imports_content+="from vox_exporter.operators.voxel.operator_${type}_exporter import EXPORT_OT_${code_name}\n"
        classes_content+="${TAB}EXPORT_OT_${code_name},\n"
    done

    sed -i " \
        s/{{imports}}/$imports_content/; \
        s/{{classes}}/$classes_content/" \
    "$output_file"

    sed -i "1i # $(get_autogenerate_notice)" "$output_file"
    echo "Generated file: $output_file"
}


if [ "$1" = "-a" ] || [ "$1" = "--all" ]; then
    read_and_process_voxel_formats
    for type in "${!formats[@]}"; do
        name="${formats[$type]}"
        if [ "$type" == "vox" ]; then
            continue
        fi
        copy_and_modify_template $type "$name"
    done
    generate_voxel_formats_menu_py_file

elif [ "$#" -eq 1 ]; then
    read_and_process_voxel_formats
    type="$1"
    if [[ ! -v formats["$type"] ]]; then
        echo "There is no support for voxel format '$type'."
        exit 1
    fi
    echo "Processing type: $type"
    name="${formats[$type]}"
    copy_and_modify_template $type "$name"
else
    echo "$(get_usage_text)"
    exit 1
fi
