# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_voxel_builder(BaseOperatorImporter):
    bl_idname = "import.voxel_builder"
    bl_label = "Voxel Builder (.vbx)"
    bl_description = "Import Voxel Builder format (.vbx)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vbx"

    filter_glob: bpy.props.StringProperty(
        default="*.vbx",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
