# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_minecraft_anvil_region(BaseOperatorImporter):
    bl_idname = "import.minecraft_anvil_region"
    bl_label = "Minecraft Anvil Region (.mca)"
    bl_description = "Import Minecraft Anvil Region format (.mca)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".mca"

    filter_glob: bpy.props.StringProperty(
        default="*.mca",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
