# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_minetest_template(BaseOperatorImporter):
    bl_idname = "import.minetest_template"
    bl_label = "Minetest Template (.mts)"
    bl_description = "Import Minetest Template format (.mts)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".mts"

    filter_glob: bpy.props.StringProperty(
        default="*.mts",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
