# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_goxel(BaseOperatorImporter):
    bl_idname = "import.goxel"
    bl_label = "Goxel (.gox)"
    bl_description = "Import Goxel format (.gox)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".gox"

    filter_glob: bpy.props.StringProperty(
        default="*.gox",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
