# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_voxel_max(BaseOperatorImporter):
    bl_idname = "import.voxel_max"
    bl_label = "Voxel Max (.vmax)"
    bl_description = "Import Voxel Max format (.vmax)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vmax"

    filter_glob: bpy.props.StringProperty(
        default="*.vmax",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
