# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_sandbox_voxedit_hierarchy(BaseOperatorImporter):
    bl_idname = "import.sandbox_voxedit_hierarchy"
    bl_label = "Sandbox VoxEdit Hierarchy (.vxr)"
    bl_description = "Import Sandbox VoxEdit Hierarchy format (.vxr)"

    filename_ext: str = ".vxr"

    filter_glob: bpy.props.StringProperty(
        default="*.vxr",
        options={'HIDDEN'},
        maxlen=255,
    )