# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_qubicle_exchange_format_ascii(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_qubicle_exchange_format_ascii"
    bl_label = "Import QEF"
    bl_description = "Import Qubicle Exchange Format ASCII format (.qef)"

    filename_ext: str = ".qef"
    voxel_type: str = "qef"
    voxel_name: str = "Qubicle Exchange Format ASCII"

    filter_glob: bpy.props.StringProperty(
        default="*.qef",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770