# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_minecraft_anvil_region(BaseOperatorImporter):
    bl_idname = "import.minecraft_anvil_region"
    bl_label = "Minecraft Anvil Region (.mca)"
    bl_description = "Import Minecraft Anvil Region format (.mca)"

    filename_ext = ".mca"

    filter_glob: bpy.props.StringProperty(
        default="*.mca",
        options={'HIDDEN'},
        maxlen=255,
    )