# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_particubes(BaseOperatorImporter):
    bl_idname = "import.particubes"
    bl_label = "Particubes (.pcubes)"
    bl_description = "Import Particubes format (.pcubes)"

    filename_ext = ".pcubes"

    filter_glob: bpy.props.StringProperty(
        default="*.pcubes",
        options={'HIDDEN'},
        maxlen=255,
    )