# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_cubeworld_cubemap(BaseOperatorImporter):
    bl_idname = "import.voxility_cubeworld_cubemap"
    bl_label = "CubeWorld CubeMap (.cub)"
    bl_description = "Import CubeWorld CubeMap format (.cub)"

    filename_ext: str = ".cub"

    filter_glob: bpy.props.StringProperty(
        default="*.cub",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770