# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_voxlap_voxel_model_format(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_voxlap_voxel_model_format"
    bl_label = "Voxlap Voxel model format (.kvx)"
    bl_description = "Import Voxlap Voxel model format format (.kvx)"

    filename_ext: str = ".kvx"

    filter_glob: bpy.props.StringProperty(
        default="*.kvx",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770