# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_minetest_template(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_minetest_template"
    bl_label = "Import MTS"
    bl_description = "Import Minetest Template format (.mts)"

    filename_ext: str = ".mts"
    voxel_type: str = "mts"
    voxel_name: str = "Minetest Template"

    filter_glob: bpy.props.StringProperty(
        default="*.mts",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770