# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_magicavoxel_xraw(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_magicavoxel_xraw"
    bl_label = "MagicaVoxel XRAW (.xraw)"
    bl_description = "Import MagicaVoxel XRAW format (.xraw)"

    filename_ext: str = ".xraw"

    filter_glob: bpy.props.StringProperty(
        default="*.xraw",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770