# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_minecraft_anvil_region(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_minecraft_anvil_region"
    bl_label = "Import MCA"
    bl_description = "Import Minecraft Anvil Region format (.mca)"

    filename_ext: str = ".mca"
    voxel_type: str = "mca"
    voxel_name: str = "Minecraft Anvil Region"

    filter_glob: bpy.props.StringProperty(
        default="*.mca",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770