# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_sandbox_voxedit_collection(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_sandbox_voxedit_collection"
    bl_label = "Import VXC"
    bl_description = "Import Sandbox VoxEdit Collection format (.vxc)"

    filename_ext: str = ".vxc"
    voxel_type: str = "vxc"
    voxel_name: str = "Sandbox VoxEdit Collection"

    filter_glob: bpy.props.StringProperty(
        default="*.vxc",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770