# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_cubzh(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_cubzh"
    bl_label = "Import 3ZH"
    bl_description = "Import Cubzh format (.3zh)"

    filename_ext: str = ".3zh"
    voxel_type: str = "3zh"
    voxel_name: str = "Cubzh"

    filter_glob: bpy.props.StringProperty(
        default="*.3zh",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770