# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_cubzh(BaseOperatorImporter):
    bl_idname = "import.cubzh"
    bl_label = "Cubzh (.3zh)"
    bl_description = "Import Cubzh format (.3zh)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".3zh"

    filter_glob: bpy.props.StringProperty(
        default="*.3zh",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
