# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_minecraft_schematic(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_minecraft_schematic"
    bl_label = "Import SCHEMATIC"
    bl_description = "Import Minecraft Schematic format (.schematic)"

    filename_ext: str = ".schematic"
    voxel_type: str = "schematic"
    voxel_name: str = "Minecraft Schematic"

    filter_glob: bpy.props.StringProperty(
        default="*.schematic",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770