# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_magicavoxel_xraw(BaseOperatorImporter):
    bl_idname = "import.magicavoxel_xraw"
    bl_label = "MagicaVoxel XRAW (.xraw)"
    bl_description = "Import MagicaVoxel XRAW format (.xraw)"

    filename_ext: str = ".xraw"

    filter_glob: bpy.props.StringProperty(
        default="*.xraw",
        options={'HIDDEN'},
        maxlen=255,
    )