# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_starmade(BaseOperatorImporter):
    bl_idname = "import.starmade"
    bl_label = "StarMade (.sment)"
    bl_description = "Import StarMade format (.sment)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".sment"

    filter_glob: bpy.props.StringProperty(
        default="*.sment",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
