# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_starmade(BaseOperatorImporter):
    bl_idname = "import.starmade"
    bl_label = "StarMade (.sment)"
    bl_description = "Import StarMade format (.sment)"

    filename_ext: str = ".sment"

    filter_glob: bpy.props.StringProperty(
        default="*.sment",
        options={'HIDDEN'},
        maxlen=255,
    )