# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_vengi(BaseOperatorImporter):
    bl_idname = "import.vengi"
    bl_label = "Vengi (.vengi)"
    bl_description = "Import Vengi format (.vengi)"

    filename_ext: str = ".vengi"

    filter_glob: bpy.props.StringProperty(
        default="*.vengi",
        options={'HIDDEN'},
        maxlen=255,
    )