# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_starmade_template(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_starmade_template"
    bl_label = "Import SMTPL"
    bl_description = "Import StarMade Template format (.smtpl)"

    filename_ext: str = ".smtpl"
    voxel_type: str = "smtpl"
    voxel_name: str = "StarMade Template"

    filter_glob: bpy.props.StringProperty(
        default="*.smtpl",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770