# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_goxel(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_goxel"
    bl_label = "Goxel (.gox)"
    bl_description = "Import Goxel format (.gox)"

    filename_ext: str = ".gox"

    filter_glob: bpy.props.StringProperty(
        default="*.gox",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770