# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_cubic_mesh(BaseOperatorImporter):
    bl_idname = "import.cubic_mesh"
    bl_label = "CuBic Mesh (.csm)"
    bl_description = "Import CuBic Mesh format (.csm)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".csm"

    filter_glob: bpy.props.StringProperty(
        default="*.csm",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
