# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_cubzh_world(BaseOperatorImporter):
    bl_idname = "import.cubzh_world"
    bl_label = "Cubzh World (.b64)"
    bl_description = "Import Cubzh World format (.b64)"

    filename_ext = ".b64"

    filter_glob: bpy.props.StringProperty(
        default="*.b64",
        options={'HIDDEN'},
        maxlen=255,
    )