# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_voxel_max(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_voxel_max"
    bl_label = "Voxel Max (.vmax)"
    bl_description = "Import Voxel Max format (.vmax)"

    filename_ext: str = ".vmax"

    filter_glob: bpy.props.StringProperty(
        default="*.vmax",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770