# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_qubicle_binary_exchange(BaseOperatorImporter):
    bl_idname = "import.qubicle_binary_exchange"
    bl_label = "Qubicle Binary Exchange (.qb)"
    bl_description = "Import Qubicle Binary Exchange format (.qb)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".qb"

    filter_glob: bpy.props.StringProperty(
        default="*.qb",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
