# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_magicavoxel(BaseOperatorImporter):
    bl_idname = "import.magicavoxel"
    bl_label = "MagicaVoxel (.vox)"
    bl_description = "Import MagicaVoxel format (.vox)"

    filename_ext = ".vox"

    filter_glob: bpy.props.StringProperty(
        default="*.vox",
        options={'HIDDEN'},
        maxlen=255,
    )