# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_particubes(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_particubes"
    bl_label = "Import PCUBES"
    bl_description = "Import Particubes format (.pcubes)"

    filename_ext: str = ".pcubes"
    voxel_type: str = "pcubes"
    voxel_name: str = "Particubes"

    filter_glob: bpy.props.StringProperty(
        default="*.pcubes",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770