# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_cubeworld_cubemap(BaseOperatorImporter):
    bl_idname = "import.cubeworld_cubemap"
    bl_label = "CubeWorld CubeMap (.cub)"
    bl_description = "Import CubeWorld CubeMap format (.cub)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".cub"

    filter_glob: bpy.props.StringProperty(
        default="*.cub",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
