# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_minecraft_schematic(BaseOperatorImporter):
    bl_idname = "import.minecraft_schematic"
    bl_label = "Minecraft Schematic (.schematic)"
    bl_description = "Import Minecraft Schematic format (.schematic)"

    filename_ext = ".schematic"

    filter_glob: bpy.props.StringProperty(
        default="*.schematic",
        options={'HIDDEN'},
        maxlen=255,
    )