# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_sproxel_csv(BaseOperatorImporter):
    bl_idname = "import.sproxel_csv"
    bl_label = "Sproxel csv (.csv)"
    bl_description = "Import Sproxel csv format (.csv)"

    filename_ext = ".csv"

    filter_glob: bpy.props.StringProperty(
        default="*.csv",
        options={'HIDDEN'},
        maxlen=255,
    )