# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_minecraft_level_dat(BaseOperatorImporter):
    bl_idname = "import.minecraft_level_dat"
    bl_label = "Minecraft level dat (.dat)"
    bl_description = "Import Minecraft level dat format (.dat)"

    filename_ext: str = ".dat"

    filter_glob: bpy.props.StringProperty(
        default="*.dat",
        options={'HIDDEN'},
        maxlen=255,
    )