# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_voxel3d(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_voxel3d"
    bl_label = "Import V3A"
    bl_description = "Import Voxel3D format (.v3a)"

    filename_ext: str = ".v3a"
    voxel_type: str = "v3a"
    voxel_name: str = "Voxel3D"

    filter_glob: bpy.props.StringProperty(
        default="*.v3a",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770