# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_binvox_command_line_voxelizer(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_binvox_command_line_voxelizer"
    bl_label = "Import BINVOX"
    bl_description = "Import Binvox command line voxelizer format (.binvox)"

    filename_ext: str = ".binvox"
    voxel_type: str = "binvox"
    voxel_name: str = "Binvox command line voxelizer"

    filter_glob: bpy.props.StringProperty(
        default="*.binvox",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770