# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_binvox_command_line_voxelizer(BaseOperatorImporter):
    bl_idname = "import.binvox_command_line_voxelizer"
    bl_label = "Binvox command line voxelizer (.binvox)"
    bl_description = "Import Binvox command line voxelizer format (.binvox)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".binvox"

    filter_glob: bpy.props.StringProperty(
        default="*.binvox",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
