# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_starmade(OperatorVoxelBaseImporter):
    bl_idname = "import.voxility_starmade"
    bl_label = "Import SMENT"
    bl_description = "Import StarMade format (.sment)"

    filename_ext: str = ".sment"
    voxel_type: str = "sment"
    voxel_name: str = "StarMade"

    filter_glob: bpy.props.StringProperty(
        default="*.sment",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770