# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_qubicle_exchange_format_ascii(BaseOperatorImporter):
    bl_idname = "import.qubicle_exchange_format_ascii"
    bl_label = "Qubicle Exchange Format ASCII (.qef)"
    bl_description = "Import Qubicle Exchange Format ASCII format (.qef)"

    filename_ext = ".qef"

    filter_glob: bpy.props.StringProperty(
        default="*.qef",
        options={'HIDDEN'},
        maxlen=255,
    )