# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_cubeworld_cubemap(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_cubeworld_cubemap"
    bl_label = "Import CUB"
    bl_description = "Import CubeWorld CubeMap format (.cub)"

    filename_ext: str = ".cub"
    voxel_type: str = "cub"
    voxel_name: str = "CubeWorld CubeMap"

    filter_glob: bpy.props.StringProperty(
        default="*.cub",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770