# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_animatoon_3d_scene(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_animatoon_3d_scene"
    bl_label = "Import SCN"
    bl_description = "Import Animatoon 3D Scene format (.scn)"

    filename_ext: str = ".scn"
    voxel_type: str = "scn"
    voxel_name: str = "Animatoon 3D Scene"

    filter_glob: bpy.props.StringProperty(
        default="*.scn",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770