# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_voxel3d(BaseOperatorImporter):
    bl_idname = "import.voxel3d"
    bl_label = "Voxel3D (.v3a)"
    bl_description = "Import Voxel3D format (.v3a)"

    filename_ext = ".v3a"

    filter_glob: bpy.props.StringProperty(
        default="*.v3a",
        options={'HIDDEN'},
        maxlen=255,
    )