# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_tiberian_sun(BaseOperatorImporter):
    bl_idname = "import.tiberian_sun"
    bl_label = "Tiberian Sun (.vxl)"
    bl_description = "Import Tiberian Sun format (.vxl)"

    filename_ext = ".vxl"

    filter_glob: bpy.props.StringProperty(
        default="*.vxl",
        options={'HIDDEN'},
        maxlen=255,
    )