# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_nicks_voxel_model(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_nicks_voxel_model"
    bl_label = "Import NVM"
    bl_description = "Import Nicks Voxel Model format (.nvm)"

    filename_ext: str = ".nvm"
    voxel_type: str = "nvm"
    voxel_name: str = "Nicks Voxel Model"

    filter_glob: bpy.props.StringProperty(
        default="*.nvm",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770