# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_importer import OperatorVoxelBaseImporter

class IMPORT_OT_sproxel_csv(OperatorVoxelBaseImporter):
    bl_idname = "import.voxelity_sproxel_csv"
    bl_label = "Import CSV"
    bl_description = "Import Sproxel csv format (.csv)"

    filename_ext: str = ".csv"
    voxel_type: str = "csv"
    voxel_name: str = "Sproxel csv"

    filter_glob: bpy.props.StringProperty(
        default="*.csv",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770