# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_nicks_voxel_model(BaseOperatorImporter):
    bl_idname = "import.nicks_voxel_model"
    bl_label = "Nicks Voxel Model (.nvm)"
    bl_description = "Import Nicks Voxel Model format (.nvm)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".nvm"

    filter_glob: bpy.props.StringProperty(
        default="*.nvm",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
