# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_qubicle_project(BaseOperatorImporter):
    bl_idname = "import.qubicle_project"
    bl_label = "Qubicle Project (.qbcl)"
    bl_description = "Import Qubicle Project format (.qbcl)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".qbcl"

    filter_glob: bpy.props.StringProperty(
        default="*.qbcl",
        options={'HIDDEN'},
        maxlen=255,
    )

    def execute(self, context):
        # Your import logic goes here
        return {'FINISHED'}
