# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_sandbox_voxedit_model(BaseOperatorImporter):
    bl_idname = "import.sandbox_voxedit_model"
    bl_label = "Sandbox VoxEdit Model (.vxm)"
    bl_description = "Import Sandbox VoxEdit Model format (.vxm)"

    filename_ext: str = ".vxm"

    filter_glob: bpy.props.StringProperty(
        default="*.vxm",
        options={'HIDDEN'},
        maxlen=255,
    )