# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_sandbox_voxedit_tilemap(BaseOperatorImporter):
    bl_idname = "import.sandbox_voxedit_tilemap"
    bl_label = "Sandbox VoxEdit Tilemap (.vxt)"
    bl_description = "Import Sandbox VoxEdit Tilemap format (.vxt)"

    filename_ext = ".vxt"

    filter_glob: bpy.props.StringProperty(
        default="*.vxt",
        options={'HIDDEN'},
        maxlen=255,
    )