# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_sandbox_voxedit_collection(BaseOperatorImporter):
    bl_idname = "import.sandbox_voxedit_collection"
    bl_label = "Sandbox VoxEdit Collection (.vxc)"
    bl_description = "Import Sandbox VoxEdit Collection format (.vxc)"

    filename_ext = ".vxc"

    filter_glob: bpy.props.StringProperty(
        default="*.vxc",
        options={'HIDDEN'},
        maxlen=255,
    )