# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_importer import BaseOperatorImporter

class IMPORT_OT_voxlap_voxel_model_format(BaseOperatorImporter):
    bl_idname = "import.voxlap_voxel_model_format"
    bl_label = "Voxlap Voxel model format (.kvx)"
    bl_description = "Import Voxlap Voxel model format format (.kvx)"

    filename_ext: str = ".kvx"

    filter_glob: bpy.props.StringProperty(
        default="*.kvx",
        options={'HIDDEN'},
        maxlen=255,
    )