# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-vox-menu-py-file.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.exporters.operator_vox_exporter import EXPORT_OT_magicavoxel
from vox_exporter.operators.voxel.exporters.operator_qb_exporter import EXPORT_OT_qubicle_binary_exchange
from vox_exporter.operators.voxel.exporters.operator_qbt_exporter import EXPORT_OT_qubicle_binary_tree_exchange
from vox_exporter.operators.voxel.exporters.operator_qef_exporter import EXPORT_OT_qubicle_exchange_format_ascii
from vox_exporter.operators.voxel.exporters.operator_qbcl_exporter import EXPORT_OT_qubicle_project
from vox_exporter.operators.voxel.exporters.operator_binvox_exporter import EXPORT_OT_binvox_command_line_voxelizer
from vox_exporter.operators.voxel.exporters.operator_cub_exporter import EXPORT_OT_cubeworld_cubemap
from vox_exporter.operators.voxel.exporters.operator_schematic_exporter import EXPORT_OT_minecraft_schematic
from vox_exporter.operators.voxel.exporters.operator_dat_exporter import EXPORT_OT_minecraft_level_dat
from vox_exporter.operators.voxel.exporters.operator_mca_exporter import EXPORT_OT_minecraft_anvil_region
from vox_exporter.operators.voxel.exporters.operator_mts_exporter import EXPORT_OT_minetest_template
from vox_exporter.operators.voxel.exporters.operator_vxc_exporter import EXPORT_OT_sandbox_voxedit_collection
from vox_exporter.operators.voxel.exporters.operator_vxr_exporter import EXPORT_OT_sandbox_voxedit_hierarchy
from vox_exporter.operators.voxel.exporters.operator_vxt_exporter import EXPORT_OT_sandbox_voxedit_tilemap
from vox_exporter.operators.voxel.exporters.operator_vxm_exporter import EXPORT_OT_sandbox_voxedit_model
from vox_exporter.operators.voxel.exporters.operator_xraw_exporter import EXPORT_OT_magicavoxel_xraw
from vox_exporter.operators.voxel.exporters.operator_vxl_exporter import EXPORT_OT_tiberian_sun
from vox_exporter.operators.voxel.exporters.operator_kv6_exporter import EXPORT_OT_voxlap_voxel_engine
from vox_exporter.operators.voxel.exporters.operator_kvx_exporter import EXPORT_OT_voxlap_voxel_model_format
from vox_exporter.operators.voxel.exporters.operator_scn_exporter import EXPORT_OT_animatoon_3d_scene
from vox_exporter.operators.voxel.exporters.operator_csv_exporter import EXPORT_OT_sproxel_csv
from vox_exporter.operators.voxel.exporters.operator_sment_exporter import EXPORT_OT_starmade
from vox_exporter.operators.voxel.exporters.operator_gox_exporter import EXPORT_OT_goxel
from vox_exporter.operators.voxel.exporters.operator_vmax_exporter import EXPORT_OT_voxel_max
from vox_exporter.operators.voxel.exporters.operator_vbx_exporter import EXPORT_OT_voxel_builder
from vox_exporter.operators.voxel.exporters.operator_v3a_exporter import EXPORT_OT_voxel3d
from vox_exporter.operators.voxel.exporters.operator_vengi_exporter import EXPORT_OT_vengi
from vox_exporter.operators.voxel.exporters.operator_nvm_exporter import EXPORT_OT_nicks_voxel_model
from vox_exporter.operators.voxel.exporters.operator_pcubes_exporter import EXPORT_OT_particubes
from vox_exporter.operators.voxel.exporters.operator_csm_exporter import EXPORT_OT_cubic_mesh
from vox_exporter.operators.voxel.exporters.operator_3zh_exporter import EXPORT_OT_cubzh


CLASSES = [
    EXPORT_OT_magicavoxel,
    EXPORT_OT_qubicle_binary_exchange,
    EXPORT_OT_qubicle_binary_tree_exchange,
    EXPORT_OT_qubicle_exchange_format_ascii,
    EXPORT_OT_qubicle_project,
    EXPORT_OT_binvox_command_line_voxelizer,
    EXPORT_OT_cubeworld_cubemap,
    EXPORT_OT_sandbox_voxedit_hierarchy,
    EXPORT_OT_sandbox_voxedit_model,
    EXPORT_OT_magicavoxel_xraw,
    EXPORT_OT_tiberian_sun,
    EXPORT_OT_voxlap_voxel_engine,
    EXPORT_OT_voxlap_voxel_model_format,
    EXPORT_OT_goxel,
    EXPORT_OT_voxel_max,
    EXPORT_OT_voxel3d,
    EXPORT_OT_vengi,
    EXPORT_OT_cubzh,
]

class VoxelFormatsExportMenu(bpy.types.Menu):
    bl_idname = "TOPBAR_MT_select_VoxelFormatsExportMenu_submenu"
    bl_label = "Select"

    def draw(self, context):
        layout = self.layout
        for cls in CLASSES:
            layout.operator(cls.bl_idname, text=cls.bl_label)

def menu_vox_export_func_callback(self, context):
    self.layout.operator(EXPORT_OT_magicavoxel.bl_idname)

def menu_VoxelFormatsExportMenu_func_callback(self, context):
    self.layout.menu(VoxelFormatsExportMenu.bl_idname, text="More Voxel Formats")

def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    bpy.utils.register_class(VoxelFormatsExportMenu)
    bpy.types.TOPBAR_MT_file_export.append(menu_vox_export_func_callback)
    bpy.types.TOPBAR_MT_file_export.append(menu_VoxelFormatsExportMenu_func_callback)

def unregister():
    for cls in CLASSES:
        bpy.utils.unregister_class(cls)
    bpy.utils.unregister_class(VoxelFormatsExportMenu)
    bpy.types.TOPBAR_MT_file_export.remove(menu_vox_export_func_callback)
    bpy.types.TOPBAR_MT_file_export.remove(menu_VoxelFormatsExportMenu_func_callback)