# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-vox-menu-py-file.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.importers.operator_vox_importer import IMPORT_OT_magicavoxel
from voxility_pro.operators.voxel.importers.operator_qb_importer import IMPORT_OT_qubicle_binary_exchange
from voxility_pro.operators.voxel.importers.operator_qbt_importer import IMPORT_OT_qubicle_binary_tree_exchange
from voxility_pro.operators.voxel.importers.operator_qef_importer import IMPORT_OT_qubicle_exchange_format_ascii
from voxility_pro.operators.voxel.importers.operator_qbcl_importer import IMPORT_OT_qubicle_project
from voxility_pro.operators.voxel.importers.operator_binvox_importer import IMPORT_OT_binvox_command_line_voxelizer
from voxility_pro.operators.voxel.importers.operator_cub_importer import IMPORT_OT_cubeworld_cubemap
from voxility_pro.operators.voxel.importers.operator_schematic_importer import IMPORT_OT_minecraft_schematic
from voxility_pro.operators.voxel.importers.operator_dat_importer import IMPORT_OT_minecraft_level_dat
from voxility_pro.operators.voxel.importers.operator_mca_importer import IMPORT_OT_minecraft_anvil_region
from voxility_pro.operators.voxel.importers.operator_mts_importer import IMPORT_OT_minetest_template
from voxility_pro.operators.voxel.importers.operator_vxc_importer import IMPORT_OT_sandbox_voxedit_collection
from voxility_pro.operators.voxel.importers.operator_vxr_importer import IMPORT_OT_sandbox_voxedit_hierarchy
from voxility_pro.operators.voxel.importers.operator_vxt_importer import IMPORT_OT_sandbox_voxedit_tilemap
from voxility_pro.operators.voxel.importers.operator_vxm_importer import IMPORT_OT_sandbox_voxedit_model
from voxility_pro.operators.voxel.importers.operator_xraw_importer import IMPORT_OT_magicavoxel_xraw
from voxility_pro.operators.voxel.importers.operator_vxl_importer import IMPORT_OT_tiberian_sun
from voxility_pro.operators.voxel.importers.operator_kv6_importer import IMPORT_OT_voxlap_voxel_engine
from voxility_pro.operators.voxel.importers.operator_kvx_importer import IMPORT_OT_voxlap_voxel_model_format
from voxility_pro.operators.voxel.importers.operator_scn_importer import IMPORT_OT_animatoon_3d_scene
from voxility_pro.operators.voxel.importers.operator_csv_importer import IMPORT_OT_sproxel_csv
from voxility_pro.operators.voxel.importers.operator_sment_importer import IMPORT_OT_starmade
from voxility_pro.operators.voxel.importers.operator_gox_importer import IMPORT_OT_goxel
from voxility_pro.operators.voxel.importers.operator_vmax_importer import IMPORT_OT_voxel_max
from voxility_pro.operators.voxel.importers.operator_vbx_importer import IMPORT_OT_voxel_builder
from voxility_pro.operators.voxel.importers.operator_v3a_importer import IMPORT_OT_voxel3d
from voxility_pro.operators.voxel.importers.operator_vengi_importer import IMPORT_OT_vengi
from voxility_pro.operators.voxel.importers.operator_nvm_importer import IMPORT_OT_nicks_voxel_model
from voxility_pro.operators.voxel.importers.operator_pcubes_importer import IMPORT_OT_particubes
from voxility_pro.operators.voxel.importers.operator_csm_importer import IMPORT_OT_cubic_mesh
from voxility_pro.operators.voxel.importers.operator_3zh_importer import IMPORT_OT_cubzh
from voxility_pro.operators.voxel.importers.operator_b64_importer import IMPORT_OT_cubzh_world


CLASSES = [
    IMPORT_OT_magicavoxel,
    IMPORT_OT_qubicle_binary_exchange,
    IMPORT_OT_qubicle_binary_tree_exchange,
    IMPORT_OT_qubicle_exchange_format_ascii,
    IMPORT_OT_qubicle_project,
    IMPORT_OT_binvox_command_line_voxelizer,
    IMPORT_OT_cubeworld_cubemap,
    IMPORT_OT_minecraft_schematic,
    IMPORT_OT_minecraft_level_dat,
    IMPORT_OT_minecraft_anvil_region,
    IMPORT_OT_minetest_template,
    IMPORT_OT_sandbox_voxedit_collection,
    IMPORT_OT_sandbox_voxedit_hierarchy,
    IMPORT_OT_sandbox_voxedit_tilemap,
    IMPORT_OT_sandbox_voxedit_model,
    IMPORT_OT_magicavoxel_xraw,
    IMPORT_OT_tiberian_sun,
    IMPORT_OT_voxlap_voxel_engine,
    IMPORT_OT_voxlap_voxel_model_format,
    IMPORT_OT_animatoon_3d_scene,
    IMPORT_OT_starmade,
    IMPORT_OT_goxel,
    IMPORT_OT_voxel_max,
    IMPORT_OT_voxel_builder,
    IMPORT_OT_voxel3d,
    IMPORT_OT_vengi,
    IMPORT_OT_nicks_voxel_model,
    IMPORT_OT_cubic_mesh,
    IMPORT_OT_cubzh,
    IMPORT_OT_cubzh_world,
]

class VoxelFormatsImportMenu(bpy.types.Menu):
    bl_idname = "TOPBAR_MT_select_VoxelFormatsImportMenu_submenu"
    bl_label = "Select"

    def draw(self, _context):
        layout = self.layout
        for cls in CLASSES:
            layout.operator(cls.bl_idname, text=cls.bl_label)

def menu_vox_import_func_callback(self, _context):
    self.layout.operator(IMPORT_OT_magicavoxel.bl_idname)

def menu_VoxelFormatsImportMenu_func_callback(self, _context):
    self.layout.menu(VoxelFormatsImportMenu.bl_idname, text="Voxility Voxel Formats")

def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    bpy.utils.register_class(VoxelFormatsImportMenu)
    bpy.types.TOPBAR_MT_file_import.append(menu_vox_import_func_callback)
    bpy.types.TOPBAR_MT_file_import.append(menu_VoxelFormatsImportMenu_func_callback)

def unregister():
    for cls in CLASSES:
        bpy.utils.unregister_class(cls)
    bpy.utils.unregister_class(VoxelFormatsImportMenu)
    bpy.types.TOPBAR_MT_file_import.remove(menu_vox_import_func_callback)
    bpy.types.TOPBAR_MT_file_import.remove(menu_VoxelFormatsImportMenu_func_callback)