#!/bin/bash

FORMATS_FILE="supported-voxel-formats.txt"

declare -A formats

process_voxel_format() {
    line=$1
    type=$(echo "$line" | awk -F ': ' '{print $1}')
    name=$(echo "$line" | awk -F ': ' '{$1=""; print $0}' | sed 's/^[[:space:]]*//')
    formats["$type"]=$name
}

read_and_process_voxel_formats() {
    while IFS= read -r line; do
        line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        if [ -z "$line" ]; then
            break
        fi
        process_voxel_format "$line"
    done < $FORMATS_FILE
}

get_usage_text() {
    echo "Usage: $0 [-a|--all] | <type> <name>"
}

copy_and_modify_template() {
    local type="$1"
    local name="$2"

    code_name=$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
    source_file="operator_{type}_exporter.template.txt"
    destination_file="operator_${type}_exporter.py"

    cp "$source_file" "$destination_file"

    sed -i "1i # This file was autogenerated and should not be edited manually. Generated by script $0" "$destination_file"
    sed -i "s/{{type}}/$type/g; s/{{name}}/$name/g; s/{{code_name}}/$code_name/g" "$destination_file"

    echo "Generated operator .$type exporter file: $destination_file"
}


if [ "$1" = "-a" ] || [ "$1" = "--all" ]; then
    read_and_process_voxel_formats
    for type in "${!formats[@]}"; do
        name="${formats[$type]}"
        if [ "$type" == "vox" ]; then
            continue
        fi
        copy_and_modify_template $type "$name"
    done

elif [ "$#" -eq 1 ]; then
    read_and_process_voxel_formats
    type="$1"
    if [[ ! -v formats["$type"] ]]; then
        echo "There is no support for voxel format '$type'."
        exit 1
    fi
    echo "Processing type: $type"
    name="${formats[$type]}"
    copy_and_modify_template $type "$name"
else
    echo "$(get_usage_text)"
    exit 1
fi
