# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_vengi(BaseOperatorExporter):
    bl_idname = "export.vengi"
    bl_label = "Vengi (.vengi)"
    bl_description = "Export selected objects to Vengi format (.vengi)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vengi"

    filter_glob: bpy.props.StringProperty(
        default="*.vengi",
        options={'HIDDEN'},
        maxlen=255,
    )
