# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minecraft_anvil_region(BaseOperatorExporter):
    bl_idname = "export.minecraft_anvil_region"
    bl_label = "Minecraft Anvil Region (.mca)"
    bl_description = "Export selected objects to Minecraft Anvil Region format (.mca)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".mca"

    filter_glob: bpy.props.StringProperty(
        default="*.mca",
        options={'HIDDEN'},
        maxlen=255,
    )
