# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sproxel_csv(BaseOperatorExporter):
    bl_idname = "export.sproxel_csv"
    bl_label = "Sproxel csv (.csv)"
    bl_description = "Export selected objects to Sproxel csv format (.csv)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".csv"

    filter_glob: bpy.props.StringProperty(
        default="*.csv",
        options={'HIDDEN'},
        maxlen=255,
    )
