# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_animatoon_3d_scene(BaseOperatorExporter):
    bl_idname = "export.animatoon_3d_scene"
    bl_label = "Animatoon 3D Scene (.scn)"
    bl_description = "Export selected objects to Animatoon 3D Scene format (.scn)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".scn"

    filter_glob: bpy.props.StringProperty(
        default="*.scn",
        options={'HIDDEN'},
        maxlen=255,
    )
