# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubic_mesh(BaseOperatorExporter):
    bl_idname = "export.cubic_mesh"
    bl_label = "CuBic Mesh (.csm)"
    bl_description = "Export selected objects to CuBic Mesh format (.csm)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".csm"

    filter_glob: bpy.props.StringProperty(
        default="*.csm",
        options={'HIDDEN'},
        maxlen=255,
    )
