# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sandbox_voxedit_collection(BaseOperatorExporter):
    bl_idname = "export.sandbox_voxedit_collection"
    bl_label = "Sandbox VoxEdit Collection (.vxc)"
    bl_description = "Export selected objects to Sandbox VoxEdit Collection format (.vxc)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vxc"

    filter_glob: bpy.props.StringProperty(
        default="*.vxc",
        options={'HIDDEN'},
        maxlen=255,
    )
