# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxel_max(BaseOperatorExporter):
    bl_idname = "export.voxel_max"
    bl_label = "Voxel Max (.vmax)"
    bl_description = "Export selected objects to Voxel Max format (.vmax)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vmax"

    filter_glob: bpy.props.StringProperty(
        default="*.vmax",
        options={'HIDDEN'},
        maxlen=255,
    )
