# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_qubicle_exchange_format_ascii(BaseOperatorExporter):
    bl_idname = "export.qubicle_exchange_format_ascii"
    bl_label = "Qubicle Exchange Format ASCII (.qef)"
    bl_description = "Export selected objects to Qubicle Exchange Format ASCII format (.qef)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".qef"

    filter_glob: bpy.props.StringProperty(
        default="*.qef",
        options={'HIDDEN'},
        maxlen=255,
    )
