# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_binvox_command_line_voxelizer(BaseOperatorExporter):
    bl_idname = "export.binvox_command_line_voxelizer"
    bl_label = "Binvox command line voxelizer (.binvox)"
    bl_description = "Export selected objects to Binvox command line voxelizer format (.binvox)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".binvox"

    filter_glob: bpy.props.StringProperty(
        default="*.binvox",
        options={'HIDDEN'},
        maxlen=255,
    )
