# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minecraft_schematic(BaseOperatorExporter):
    bl_idname = "export.minecraft_schematic"
    bl_label = "Minecraft Schematic (.schematic)"
    bl_description = "Export selected objects to Minecraft Schematic format (.schematic)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".schematic"

    filter_glob: bpy.props.StringProperty(
        default="*.schematic",
        options={'HIDDEN'},
        maxlen=255,
    )
