# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sandbox_voxedit_tilemap(BaseOperatorExporter):
    bl_idname = "export.sandbox_voxedit_tilemap"
    bl_label = "Sandbox VoxEdit Tilemap (.vxt)"
    bl_description = "Export selected objects to Sandbox VoxEdit Tilemap format (.vxt)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vxt"

    filter_glob: bpy.props.StringProperty(
        default="*.vxt",
        options={'HIDDEN'},
        maxlen=255,
    )
