# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_starmade_blueprint(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_starmade_blueprint"
    bl_label = "Export SMENT"
    bl_description = "Export selected objects to StarMade Blueprint format (.sment)"

    filename_ext: str = ".sment"
    voxel_type: str = "sment"
    voxel_name: str = "StarMade Blueprint"

    filter_glob: bpy.props.StringProperty(
        default="*.sment",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770