# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_animatoon_3d_scene(BaseOperatorExporter):
    bl_idname = "export.voxility_animatoon_3d_scene"
    bl_label = "Animatoon 3D Scene (.scn)"
    bl_description = "Export selected objects to Animatoon 3D Scene format (.scn)"

    filename_ext: str = ".scn"

    filter_glob: bpy.props.StringProperty(
        default="*.scn",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770