# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_qubicle_exchange_format_ascii(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_qubicle_exchange_format_ascii"
    bl_label = "Qubicle Exchange Format ASCII (.qef)"
    bl_description = "Export selected objects to Qubicle Exchange Format ASCII format (.qef)"

    filename_ext: str = ".qef"

    filter_glob: bpy.props.StringProperty(
        default="*.qef",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770