# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_magicavoxel(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_magicavoxel"
    bl_label = "Export VOX"
    bl_description = "Export selected objects to MagicaVoxel format (.vox)"

    filename_ext: str = ".vox"
    voxel_type: str = "vox"
    voxel_name: str = "MagicaVoxel"

    filter_glob: bpy.props.StringProperty(
        default="*.vox",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770