# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_cubzh(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_cubzh"
    bl_label = "Export 3ZH"
    bl_description = "Export selected objects to Cubzh format (.3zh)"

    filename_ext: str = ".3zh"
    voxel_type: str = "3zh"
    voxel_name: str = "Cubzh"

    filter_glob: bpy.props.StringProperty(
        default="*.3zh",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770