# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_sandbox_voxedit_tilemap(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_sandbox_voxedit_tilemap"
    bl_label = "Export VXT"
    bl_description = "Export selected objects to Sandbox VoxEdit Tilemap format (.vxt)"

    filename_ext: str = ".vxt"
    voxel_type: str = "vxt"
    voxel_name: str = "Sandbox VoxEdit Tilemap"

    filter_glob: bpy.props.StringProperty(
        default="*.vxt",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770