# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sandbox_voxedit_model(BaseOperatorExporter):
    bl_idname = "export.sandbox_voxedit_model"
    bl_label = "Sandbox VoxEdit Model (.vxm)"
    bl_description = "Export selected objects to Sandbox VoxEdit Model format (.vxm)"

    filename_ext = ".vxm"

    filter_glob: bpy.props.StringProperty(
        default="*.vxm",
        options={'HIDDEN'},
        maxlen=255,
    )