# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_nicks_voxel_model(BaseOperatorExporter):
    bl_idname = "export.nicks_voxel_model"
    bl_label = "Nicks Voxel Model (.nvm)"
    bl_description = "Export selected objects to Nicks Voxel Model format (.nvm)"

    filename_ext = ".nvm"

    filter_glob: bpy.props.StringProperty(
        default="*.nvm",
        options={'HIDDEN'},
        maxlen=255,
    )