# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_goxel(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_goxel"
    bl_label = "Export GOX"
    bl_description = "Export selected objects to Goxel format (.gox)"

    filename_ext: str = ".gox"
    voxel_type: str = "gox"
    voxel_name: str = "Goxel"

    filter_glob: bpy.props.StringProperty(
        default="*.gox",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770