# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sandbox_voxedit_hierarchy(BaseOperatorExporter):
    bl_idname = "export.sandbox_voxedit_hierarchy"
    bl_label = "Sandbox VoxEdit Hierarchy (.vxr)"
    bl_description = "Export selected objects to Sandbox VoxEdit Hierarchy format (.vxr)"

    filename_ext: str = ".vxr"

    filter_glob: bpy.props.StringProperty(
        default="*.vxr",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770