# This file was autogenerated and should not be edited manually. Generated by script ./scripts/generate-op-exporter.sh
import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxel_builder(BaseOperatorExporter):
    bl_idname = "export.voxel_builder"
    bl_label = "Voxel Builder (.vbx)"
    bl_description = "Export selected objects to Voxel Builder format (.vbx)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vbx"

    filter_glob: bpy.props.StringProperty(
        default="*.vbx",
        options={'HIDDEN'},
        maxlen=255,
    )
