# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minetest_template(BaseOperatorExporter):
    bl_idname = "export.voxility_minetest_template"
    bl_label = "Minetest Template (.mts)"
    bl_description = "Export selected objects to Minetest Template format (.mts)"

    filename_ext: str = ".mts"

    filter_glob: bpy.props.StringProperty(
        default="*.mts",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770