# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubzh_world(BaseOperatorExporter):
    bl_idname = "export.voxility_cubzh_world"
    bl_label = "Cubzh World (.b64)"
    bl_description = "Export selected objects to Cubzh World format (.b64)"

    filename_ext: str = ".b64"

    filter_glob: bpy.props.StringProperty(
        default="*.b64",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770