# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_binvox_command_line_voxelizer(BaseOperatorExporter):
    bl_idname = "export.voxility_binvox_command_line_voxelizer"
    bl_label = "Binvox command line voxelizer (.binvox)"
    bl_description = "Export selected objects to Binvox command line voxelizer format (.binvox)"

    filename_ext: str = ".binvox"

    filter_glob: bpy.props.StringProperty(
        default="*.binvox",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770