# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxlap_voxel_engine(BaseOperatorExporter):
    bl_idname = "export.voxlap_voxel_engine"
    bl_label = "Voxlap Voxel Engine (.kv6)"
    bl_description = "Export selected objects to Voxlap Voxel Engine format (.kv6)"

    filename_ext: str = ".kv6"

    filter_glob: bpy.props.StringProperty(
        default="*.kv6",
        options={'HIDDEN'},
        maxlen=255,
    )