# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_particubes(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_particubes"
    bl_label = "Particubes (.pcubes)"
    bl_description = "Export selected objects to Particubes format (.pcubes)"

    filename_ext: str = ".pcubes"

    filter_glob: bpy.props.StringProperty(
        default="*.pcubes",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770