# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_animatoon_3d_scene(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_animatoon_3d_scene"
    bl_label = "Export SCN"
    bl_description = "Export selected objects to Animatoon 3D Scene format (.scn)"

    filename_ext: str = ".scn"
    voxel_type: str = "scn"
    voxel_name: str = "Animatoon 3D Scene"

    filter_glob: bpy.props.StringProperty(
        default="*.scn",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770