# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_nicks_voxel_model(BaseOperatorExporter):
    bl_idname = "export.voxility_nicks_voxel_model"
    bl_label = "Nicks Voxel Model (.nvm)"
    bl_description = "Export selected objects to Nicks Voxel Model format (.nvm)"

    filename_ext: str = ".nvm"

    filter_glob: bpy.props.StringProperty(
        default="*.nvm",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770