# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_tiberian_sun(BaseOperatorExporter):
    bl_idname = "export.tiberian_sun"
    bl_label = "Tiberian Sun (.vxl)"
    bl_description = "Export selected objects to Tiberian Sun format (.vxl)"

    filename_ext = ".vxl"

    filter_glob: bpy.props.StringProperty(
        default="*.vxl",
        options={'HIDDEN'},
        maxlen=255,
    )