# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_voxel_max(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_voxel_max"
    bl_label = "Export VMAX"
    bl_description = "Export selected objects to Voxel Max format (.vmax)"

    filename_ext: str = ".vmax"
    voxel_type: str = "vmax"
    voxel_name: str = "Voxel Max"

    filter_glob: bpy.props.StringProperty(
        default="*.vmax",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770