# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from vox_exporter.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_goxel(BaseOperatorExporter):
    bl_idname = "export.goxel"
    bl_label = "Goxel (.gox)"
    bl_description = "Export selected objects to Goxel format (.gox)"

    filename_ext = ".gox"

    filter_glob: bpy.props.StringProperty(
        default="*.gox",
        options={'HIDDEN'},
        maxlen=255,
    )