# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_starmade(BaseOperatorExporter):
    bl_idname = "export.starmade"
    bl_label = "StarMade (.sment)"
    bl_description = "Export selected objects to StarMade format (.sment)"

    filename_ext: str = ".sment"

    filter_glob: bpy.props.StringProperty(
        default="*.sment",
        options={'HIDDEN'},
        maxlen=255,
    )