# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_voxel3d(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_voxel3d"
    bl_label = "Voxel3D (.v3a)"
    bl_description = "Export selected objects to Voxel3D format (.v3a)"

    filename_ext: str = ".v3a"

    filter_glob: bpy.props.StringProperty(
        default="*.v3a",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770