# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_cubic_mesh(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_cubic_mesh"
    bl_label = "Export CSM"
    bl_description = "Export selected objects to CuBic Mesh format (.csm)"

    filename_ext: str = ".csm"
    voxel_type: str = "csm"
    voxel_name: str = "CuBic Mesh"

    filter_glob: bpy.props.StringProperty(
        default="*.csm",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770