# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_particubes(BaseOperatorExporter):
    bl_idname = "export.particubes"
    bl_label = "Particubes (.pcubes)"
    bl_description = "Export selected objects to Particubes format (.pcubes)"

    filename_ext = ".pcubes"

    filter_glob: bpy.props.StringProperty(
        default="*.pcubes",
        options={'HIDDEN'},
        maxlen=255,
    )