# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_sandbox_voxedit_model(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_sandbox_voxedit_model"
    bl_label = "Export VXM"
    bl_description = "Export selected objects to Sandbox VoxEdit Model format (.vxm)"

    filename_ext: str = ".vxm"
    voxel_type: str = "vxm"
    voxel_name: str = "Sandbox VoxEdit Model"

    filter_glob: bpy.props.StringProperty(
        default="*.vxm",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770