# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_magicavoxel_xraw(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_magicavoxel_xraw"
    bl_label = "Export XRAW"
    bl_description = "Export selected objects to MagicaVoxel XRAW format (.xraw)"

    filename_ext: str = ".xraw"
    voxel_type: str = "xraw"
    voxel_name: str = "MagicaVoxel XRAW"

    filter_glob: bpy.props.StringProperty(
        default="*.xraw",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770