# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minecraft_anvil_region(BaseOperatorExporter):
    bl_idname = "export.minecraft_anvil_region"
    bl_label = "Minecraft Anvil Region (.mca)"
    bl_description = "Export selected objects to Minecraft Anvil Region format (.mca)"

    filename_ext: str = ".mca"

    filter_glob: bpy.props.StringProperty(
        default="*.mca",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770