# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_qubicle_binary_exchange(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_qubicle_binary_exchange"
    bl_label = "Export QB"
    bl_description = "Export selected objects to Qubicle Binary Exchange format (.qb)"

    filename_ext: str = ".qb"
    voxel_type: str = "qb"
    voxel_name: str = "Qubicle Binary Exchange"

    filter_glob: bpy.props.StringProperty(
        default="*.qb",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770