# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_qubicle_project(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_qubicle_project"
    bl_label = "Export QBCL"
    bl_description = "Export selected objects to Qubicle Project format (.qbcl)"

    filename_ext: str = ".qbcl"
    voxel_type: str = "qbcl"
    voxel_name: str = "Qubicle Project"

    filter_glob: bpy.props.StringProperty(
        default="*.qbcl",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770