# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubeworld_cubemap(BaseOperatorExporter):
    bl_idname = "export.cubeworld_cubemap"
    bl_label = "CubeWorld CubeMap (.cub)"
    bl_description = "Export selected objects to CubeWorld CubeMap format (.cub)"

    filename_ext = ".cub"

    filter_glob: bpy.props.StringProperty(
        default="*.cub",
        options={'HIDDEN'},
        maxlen=255,
    )