# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_qubicle_binary_tree_exchange(BaseOperatorExporter):
    bl_idname = "export.qubicle_binary_tree_exchange"
    bl_label = "Qubicle Binary Tree Exchange (.qbt)"
    bl_description = "Export selected objects to Qubicle Binary Tree Exchange format (.qbt)"

    filename_ext = ".qbt"

    filter_glob: bpy.props.StringProperty(
        default="*.qbt",
        options={'HIDDEN'},
        maxlen=255,
    )