# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_qubicle_binary_tree_exchange(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_qubicle_binary_tree_exchange"
    bl_label = "Export QBT"
    bl_description = "Export selected objects to Qubicle Binary Tree Exchange format (.qbt)"

    filename_ext: str = ".qbt"
    voxel_type: str = "qbt"
    voxel_name: str = "Qubicle Binary Tree Exchange"

    filter_glob: bpy.props.StringProperty(
        default="*.qbt",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770