# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_starmade_template(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_starmade_template"
    bl_label = "Export SMTPL"
    bl_description = "Export selected objects to StarMade Template format (.smtpl)"

    filename_ext: str = ".smtpl"
    voxel_type: str = "smtpl"
    voxel_name: str = "StarMade Template"

    filter_glob: bpy.props.StringProperty(
        default="*.smtpl",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770