# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_sandbox_voxedit_hierarchy(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_sandbox_voxedit_hierarchy"
    bl_label = "Export VXR"
    bl_description = "Export selected objects to Sandbox VoxEdit Hierarchy format (.vxr)"

    filename_ext: str = ".vxr"
    voxel_type: str = "vxr"
    voxel_name: str = "Sandbox VoxEdit Hierarchy"

    filter_glob: bpy.props.StringProperty(
        default="*.vxr",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770