# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_qubicle_project(BaseOperatorExporter):
    bl_idname = "export.qubicle_project"
    bl_label = "Qubicle Project (.qbcl)"
    bl_description = "Export selected objects to Qubicle Project format (.qbcl)"

    filename_ext = ".qbcl"

    filter_glob: bpy.props.StringProperty(
        default="*.qbcl",
        options={'HIDDEN'},
        maxlen=255,
    )