# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubzh(BaseOperatorExporter):
    bl_idname = "export.cubzh"
    bl_label = "Cubzh (.3zh)"
    bl_description = "Export selected objects to Cubzh format (.3zh)"

    filename_ext: str = ".3zh"

    filter_glob: bpy.props.StringProperty(
        default="*.3zh",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770