# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubzh_world(BaseOperatorExporter):
    bl_idname = "export.cubzh_world"
    bl_label = "Cubzh World (.b64)"
    bl_description = "Export selected objects to Cubzh World format (.b64)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".b64"

    filter_glob: bpy.props.StringProperty(
        default="*.b64",
        options={'HIDDEN'},
        maxlen=255,
    )
