# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_qubicle_binary_exchange(BaseOperatorExporter):
    bl_idname = "export.qubicle_binary_exchange"
    bl_label = "Qubicle Binary Exchange (.qb)"
    bl_description = "Export selected objects to Qubicle Binary Exchange format (.qb)"

    filename_ext: str = ".qb"

    filter_glob: bpy.props.StringProperty(
        default="*.qb",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770