# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxelity_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_voxlap_voxel_model_format(OperatorVoxelBaseExporter):
    bl_idname = "export.voxelity_voxlap_voxel_model_format"
    bl_label = "Export KVX"
    bl_description = "Export selected objects to Voxlap Voxel model format format (.kvx)"

    filename_ext: str = ".kvx"
    voxel_type: str = "kvx"
    voxel_name: str = "Voxlap Voxel model format"

    filter_glob: bpy.props.StringProperty(
        default="*.kvx",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770