# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxlap_voxel_engine(BaseOperatorExporter):
    bl_idname = "export.voxility_voxlap_voxel_engine"
    bl_label = "Voxlap Voxel Engine (.kv6)"
    bl_description = "Export selected objects to Voxlap Voxel Engine format (.kv6)"

    filename_ext: str = ".kv6"

    filter_glob: bpy.props.StringProperty(
        default="*.kv6",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770