# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.operator_voxel_base_exporter import OperatorVoxelBaseExporter

class EXPORT_OT_tiberian_sun(OperatorVoxelBaseExporter):
    bl_idname = "export.voxility_tiberian_sun"
    bl_label = "Export VXL"
    bl_description = "Export selected objects to Tiberian Sun format (.vxl)"

    filename_ext: str = ".vxl"
    voxel_type: str = "vxl"
    voxel_name: str = "Tiberian Sun"

    filter_glob: bpy.props.StringProperty(
        default="*.vxl",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770