# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-op-exporter.sh
# ============================================================================

import bpy

from voxility_pro.operators.voxel.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minecraft_schematic(BaseOperatorExporter):
    bl_idname = "export.voxility_minecraft_schematic"
    bl_label = "Minecraft Schematic (.schematic)"
    bl_description = "Export selected objects to Minecraft Schematic format (.schematic)"

    filename_ext: str = ".schematic"

    filter_glob: bpy.props.StringProperty(
        default="*.schematic",
        options={'HIDDEN'},
        maxlen=255,
    ) # type: ignore https://blender.stackexchange.com/questions/311578/how-do-you-correctly-add-ui-elements-to-adhere-to-the-typing-spec/311770#311770