#!/bin/bash

MENUS_DIR="menus/"
VOX_FORMATS_MENU_TEMPLATE="voxel_formats_menu.py.template.txt"
VOX_FORMATS_MENU_FILE="voxel_formats_export_menu.py"
VOX_OPERATORS_DIR="operators/voxel/"
VOX_OPERATOR_TEMPLATE="operator_{type}_exporter.template.txt"
FORMATS_FILE="supported-voxel-formats.txt"
TAB="    "

if ! command -v jq &> /dev/null; then
    echo "jq is not installed. Please install it before running the script."
    exit 1
fi

JSON=$(cat "supported-voxel-formats.json")

get_voxel_format_name() {
    local extension="$1"
    local file_content="$2"
    local name=$(echo "$file_content" | jq -r --arg ext "$extension" '.[] | select(.extension == $ext) | .name')
    echo $name
}

get_voxel_format_saving_state() {
    local extension="$1"
    local file_content="$2"
    local saving_state=$(echo "$file_content" | jq -r --arg ext "$extension" '.[] | select(.extension == $ext) | .saving')
    echo $([ -n "$saving_state" ] && [ "$saving_state" -ne 0 ] && echo "1" || echo "")
}

get_voxel_format_bugged_state() {
    local extension="$1"
    local file_content="$2"
    local bugged_state=$(echo "$file_content" | jq -r --arg ext "$extension" '.[] | select(.extension == $ext) | .bugged')
    echo $([ -n "$bugged_state" ] && [ "$bugged_state" -ne 0 ] && echo "1" || echo "")
}

get_usage_text() {
    echo "Usage: $0 [-a|--all] | <type> <name>"
}

get_code_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '_'
}

get_autogenerate_notice() {
    echo "This file was autogenerated and should not be edited manually. Generated by script $0"
}

copy_and_modify_template() {
    local type="$1"
    local name="$2"

    code_name=$(get_code_name "$name")
    source_file="${VOX_OPERATORS_DIR}${VOX_OPERATOR_TEMPLATE}"
    destination_file="${VOX_OPERATORS_DIR}operator_${type}_exporter.py"

    cp "$source_file" "$destination_file"

    sed -i "1i # $(get_autogenerate_notice)" "$destination_file"
    sed -i "s/{{type}}/$type/g; s/{{name}}/$name/g; s/{{code_name}}/$code_name/g" "$destination_file"

    #echo "${TAB}bpy.utils.register_class(EXPORT_OT_$code_name)"
    #echo "from vox_exporter.operators.voxel.operator_${type}_exporter import EXPORT_OT_$code_name"
    echo "Generated operator .$type exporter file: $destination_file"
}

generate_voxel_formats_menu_py_file() {
    template_file="${MENUS_DIR}${VOX_FORMATS_MENU_TEMPLATE}"
    output_file="${MENUS_DIR}${VOX_FORMATS_MENU_FILE}"

    imports_content=""
    classes_content=""

    cp "$template_file" "$output_file"

    extensions=$(echo "$JSON" | jq -r '.[].extension')

    for type in $extensions; do
        if [ "$type" == "vox" ]; then
            continue
        fi
        name=$(get_voxel_format_name "$type" "$JSON")
        code_name=$(get_code_name "$name")

        imports_content+="from vox_exporter.operators.voxel.operator_${type}_exporter import EXPORT_OT_${code_name}\n"
        save=$(get_voxel_format_saving_state "$type" "$JSON")
        bugged=$(get_voxel_format_bugged_state "$type" "$JSON")
        if [ -n "$save" ] && [ "$save" -ne 0 ] && [ "$bugged" != '1' ]; then
            classes_content+="${TAB}EXPORT_OT_${code_name},\n"
        fi
    done

    sed -i " \
        s/{{imports}}/$imports_content/; \
        s/{{classes}}/$classes_content/" \
    "$output_file"

    sed -i "1i # $(get_autogenerate_notice)" "$output_file"
    echo "Generated file: $output_file"
}


if [ "$1" = "-a" ] || [ "$1" = "--all" ]; then
    extensions=$(echo "$JSON" | jq -r '.[].extension')
    for type in $extensions; do
        if [ "$type" == "vox" ]; then
            continue
        fi
        name=$(get_voxel_format_name "$type" "$JSON")
        copy_and_modify_template $type "$name"
    done
    generate_voxel_formats_menu_py_file

elif [ "$#" -eq 1 ]; then
    type="$1"
    name=$(get_voxel_format_name "$type" "$JSON")
    if [ -z "$name" ]; then
        echo "There is no support for voxel format '$type'."
        exit 1
    fi
    echo "Processing type: $type"
    copy_and_modify_template $type "$name"
else
    echo "$(get_usage_text)"
    exit 1
fi
