#!/bin/bash

MENUS_DIR="menus/"
VOX_FORMATS_MENU_TEMPLATE="voxel_formats_menu.py.template.txt"
VOX_OP_BASE_DIR="operators/voxel/"
FORMATS_FILE="supported-voxel-formats.txt"
TAB="    "

if ! command -v jq &> /dev/null; then
    echo "jq is not installed. Please install it before running the script."
    exit 1
fi

JSON=$(cat "supported-voxel-formats.json")

get_vox_column_value() {
    local extension="$1"
    local file_content="$2"
    echo "$file_content" | jq -r --arg ext "$extension" --arg column "$3" '.[] | select(.extension == $ext) | .[$column]'
}

get_usage_text() {
    echo "Usage: $0 [-a|--all] | <type> <name>"
}

get_code_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '_'
}

get_autogenerate_notice() {
    echo "This file was autogenerated and should not be edited manually. Generated by script $0"
}

copy_and_modify_template() {
    local type="$1"
    local name="$2"

    code_name=$(get_code_name "$name")
    source_file="${VOX_OP_BASE_DIR}operator_{type}_${3}er.template.txt"
    destination_file="${VOX_OP_BASE_DIR}${3}ers/operator_${type}_${3}er.py"

    cp "$source_file" "$destination_file"

    sed -i "1i # $(get_autogenerate_notice)" "$destination_file"
    sed -i "s/{{type}}/$type/g; s/{{name}}/$name/g; s/{{code_name}}/$code_name/g" "$destination_file"

    echo "Generated operator .$type ${3}er file: $destination_file"
}

generate_voxel_formats_menu_py_file() {
    template_file="${MENUS_DIR}${VOX_FORMATS_MENU_TEMPLATE}"
    output_file="${MENUS_DIR}voxel_formats_${1}_menu.py"

    imports_content=""
    classes_content=""

    cp "$template_file" "$output_file"

    extensions=$(echo "$JSON" | jq -r '.[].extension')

    for type in $extensions; do
        if [ "$type" == "vox" ]; then
            continue
        fi
        name=$(get_vox_column_value "$type" "$JSON" "name")
        code_name=$(get_code_name "$name")

        import_path="vox_exporter.$(echo ${VOX_OP_BASE_DIR}${1}ers/ | sed 's/\//./g')operator_${type}_${1}er"
        class_prefix="$(echo "$1" | tr '[:lower:]' '[:upper:]')_OT_"
        module="${class_prefix}${code_name}"
        imports_content+="from ${import_path} import ${module}\n"
        load=$(get_vox_column_value "$type" "$JSON" "loading")
        save=$(get_vox_column_value "$type" "$JSON" "saving")
        bugged=$(get_vox_column_value "$type" "$JSON" "bugged")
        if [ "$bugged" == '1' ]; then
            continue
        fi
        if ([ "$1" == 'export' ] && [ "$save" == '1' ]) || ([ "$1" == 'import' ] && [ "$load" == '1' ]); then
            classes_content+="${TAB}${class_prefix}${code_name},\n"
        fi
    done

    sed -i " \
        s/{{imports}}/$imports_content/; \
        s/{{classes}}/$classes_content/" \
    "$output_file"
    sed -i "s/{{menu_class}}/VoxelFormats${1^}Menu/g" "$output_file"
    sed -i "s/{{import-export}}/${1}/g" "$output_file"
    sed -i "1i # $(get_autogenerate_notice)" "$output_file"
    echo "Generated file: $output_file"
}

generate_op_files() {
    extensions=$(echo "$JSON" | jq -r '.[].extension')
    for type in $extensions; do
        if [ "$type" == "vox" ]; then
            continue
        fi
        name=$(get_vox_column_value "$type" "$JSON" "name")
        copy_and_modify_template $type "$name" "$1"
    done
    generate_voxel_formats_menu_py_file "$1"
}

if [ "$1" = "-a" ] || [ "$1" = "--all" ]; then
    generate_op_files "import"
    generate_op_files "export"

elif [ "$#" -eq 1 ]; then
    type="$1"
    name=$(get_vox_column_value "$type" "$JSON" "name")
    if [ -z "$name" ]; then
        echo "There is no support for voxel format '$type'."
        exit 1
    fi
    echo "Processing type: $type"
    copy_and_modify_template $type "$name"
else
    echo "$(get_usage_text)"
    exit 1
fi
