TAB="    "

get_code_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '_'
}

get_autogenerate_notice() {
    echo "\
# ============================================================================\n\
# Author: Harry McKenzie\n\
# This file was autogenerated and should not be edited manually.\n\
# Generated by script $0\n\
# ============================================================================\n"
}

get_vox_column_value() {
    local extension="$1"
    local content="$2"
    echo "$content" | jq -r --arg ext "$extension" --arg column "$3" '.[] | select(.extension == $ext) | .[$column]'
}