# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_particubes(BaseOperatorExporter):
    bl_idname = "export.particubes"
    bl_label = "Particubes (.pcubes)"
    bl_description = "Export selected objects to Particubes format (.pcubes)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".pcubes"

    filter_glob: bpy.props.StringProperty(
        default="*.pcubes",
        options={'HIDDEN'},
        maxlen=255,
    )
