# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sandbox(BaseOperatorExporter):
    bl_idname = "export.sandbox"
    bl_label = "Sandbox (.vxc)"
    bl_description = "Export selected objects to Sandbox format (.vxc)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vxc"

    filter_glob: bpy.props.StringProperty(
        default="*.vxc",
        options={'HIDDEN'},
        maxlen=255,
    )
