# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxel(BaseOperatorExporter):
    bl_idname = "export.voxel"
    bl_label = "Voxel (.vmax)"
    bl_description = "Export selected objects to Voxel format (.vmax)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vmax"

    filter_glob: bpy.props.StringProperty(
        default="*.vmax",
        options={'HIDDEN'},
        maxlen=255,
    )
