# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxlap(BaseOperatorExporter):
    bl_idname = "export.voxlap"
    bl_label = "Voxlap (.kvx)"
    bl_description = "Export selected objects to Voxlap format (.kvx)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".kvx"

    filter_glob: bpy.props.StringProperty(
        default="*.kvx",
        options={'HIDDEN'},
        maxlen=255,
    )
