# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minecraft(BaseOperatorExporter):
    bl_idname = "export.minecraft"
    bl_label = "Minecraft (.mca)"
    bl_description = "Export selected objects to Minecraft format (.mca)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".mca"

    filter_glob: bpy.props.StringProperty(
        default="*.mca",
        options={'HIDDEN'},
        maxlen=255,
    )
