# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_sproxel(BaseOperatorExporter):
    bl_idname = "export.sproxel"
    bl_label = "Sproxel (.csv)"
    bl_description = "Export selected objects to Sproxel format (.csv)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".csv"

    filter_glob: bpy.props.StringProperty(
        default="*.csv",
        options={'HIDDEN'},
        maxlen=255,
    )
