# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubeworld(BaseOperatorExporter):
    bl_idname = "export.cubeworld"
    bl_label = "CubeWorld (.cub)"
    bl_description = "Export selected objects to CubeWorld format (.cub)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".cub"

    filter_glob: bpy.props.StringProperty(
        default="*.cub",
        options={'HIDDEN'},
        maxlen=255,
    )
