# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_cubic(BaseOperatorExporter):
    bl_idname = "export.cubic"
    bl_label = "CuBic (.csm)"
    bl_description = "Export selected objects to CuBic format (.csm)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".csm"

    filter_glob: bpy.props.StringProperty(
        default="*.csm",
        options={'HIDDEN'},
        maxlen=255,
    )
