# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_animatoon(BaseOperatorExporter):
    bl_idname = "export.animatoon"
    bl_label = "Animatoon (.scn)"
    bl_description = "Export selected objects to Animatoon format (.scn)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".scn"

    filter_glob: bpy.props.StringProperty(
        default="*.scn",
        options={'HIDDEN'},
        maxlen=255,
    )
