# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_magicavoxel(BaseOperatorExporter):
    bl_idname = "export.magicavoxel"
    bl_label = "MagicaVoxel (.xraw)"
    bl_description = "Export selected objects to MagicaVoxel format (.xraw)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".xraw"

    filter_glob: bpy.props.StringProperty(
        default="*.xraw",
        options={'HIDDEN'},
        maxlen=255,
    )
