# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_minetest(BaseOperatorExporter):
    bl_idname = "export.minetest"
    bl_label = "Minetest (.mts)"
    bl_description = "Export selected objects to Minetest format (.mts)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".mts"

    filter_glob: bpy.props.StringProperty(
        default="*.mts",
        options={'HIDDEN'},
        maxlen=255,
    )
