# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_tiberian(BaseOperatorExporter):
    bl_idname = "export.tiberian"
    bl_label = "Tiberian (.vxl)"
    bl_description = "Export selected objects to Tiberian format (.vxl)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".vxl"

    filter_glob: bpy.props.StringProperty(
        default="*.vxl",
        options={'HIDDEN'},
        maxlen=255,
    )
