# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_goxel(BaseOperatorExporter):
    bl_idname = "export.goxel"
    bl_label = "Goxel (.gox)"
    bl_description = "Export selected objects to Goxel format (.gox)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".gox"

    filter_glob: bpy.props.StringProperty(
        default="*.gox",
        options={'HIDDEN'},
        maxlen=255,
    )
