# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_nicks(BaseOperatorExporter):
    bl_idname = "export.nicks"
    bl_label = "Nicks (.nvm)"
    bl_description = "Export selected objects to Nicks format (.nvm)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".nvm"

    filter_glob: bpy.props.StringProperty(
        default="*.nvm",
        options={'HIDDEN'},
        maxlen=255,
    )
