# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_binvox(BaseOperatorExporter):
    bl_idname = "export.binvox"
    bl_label = "Binvox (.binvox)"
    bl_description = "Export selected objects to Binvox format (.binvox)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".binvox"

    filter_glob: bpy.props.StringProperty(
        default="*.binvox",
        options={'HIDDEN'},
        maxlen=255,
    )
