# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_qubicle(BaseOperatorExporter):
    bl_idname = "export.qubicle"
    bl_label = "Qubicle (.qef)"
    bl_description = "Export selected objects to Qubicle format (.qef)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".qef"

    filter_glob: bpy.props.StringProperty(
        default="*.qef",
        options={'HIDDEN'},
        maxlen=255,
    )
