# This file was autogenerated and should not be edited manually. Generated by script ./generate-op-exporter.sh
import bpy

from vox_exporter.operators.base_operator_exporter import BaseOperatorExporter

class EXPORT_OT_voxel3d(BaseOperatorExporter):
    bl_idname = "export.voxel3d"
    bl_label = "Voxel3D (.v3a)"
    bl_description = "Export selected objects to Voxel3D format (.v3a)"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".v3a"

    filter_glob: bpy.props.StringProperty(
        default="*.v3a",
        options={'HIDDEN'},
        maxlen=255,
    )
