# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-addon-preferences-file.sh
# ============================================================================

import bpy
import bpy_types

def update_bool_property(self, context: bpy_types.Context) -> None:

    if self.type_vox:
        pass
    if self.type_qb:
        pass
    if self.type_qbt:
        pass
    if self.type_qef:
        pass
    if self.type_qbcl:
        pass
    if self.type_binvox:
        pass
    if self.type_cub:
        pass
    if self.type_schematic:
        pass
    if self.type_dat:
        pass
    if self.type_mca:
        pass
    if self.type_mts:
        pass
    if self.type_vxc:
        pass
    if self.type_vxr:
        pass
    if self.type_vxt:
        pass
    if self.type_vxm:
        pass
    if self.type_xraw:
        pass
    if self.type_vxl:
        pass
    if self.type_kv6:
        pass
    if self.type_kvx:
        pass
    if self.type_scn:
        pass
    if self.type_csv:
        pass
    if self.type_sment:
        pass
    if self.type_gox:
        pass
    if self.type_vmax:
        pass
    if self.type_vbx:
        pass
    if self.type_v3a:
        pass
    if self.type_vengi:
        pass
    if self.type_nvm:
        pass
    if self.type_pcubes:
        pass
    if self.type_csm:
        pass
    if self.type_3zh:
        pass
    if self.type_b64:
        pass

class AddonPreferences(bpy.types.AddonPreferences):
    bl_idname = "voxility_pro" # __name__ if the class is defined inside __init__.py

    type_vox: bpy.props.BoolProperty(
        name="*.vox (MagicaVoxel)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qb: bpy.props.BoolProperty(
        name="*.qb (Qubicle Binary Exchange)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qbt: bpy.props.BoolProperty(
        name="*.qbt (Qubicle Binary Tree Exchange)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qef: bpy.props.BoolProperty(
        name="*.qef (Qubicle Exchange Format ASCII)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qbcl: bpy.props.BoolProperty(
        name="*.qbcl (Qubicle Project)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_binvox: bpy.props.BoolProperty(
        name="*.binvox (Binvox command line voxelizer)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_cub: bpy.props.BoolProperty(
        name="*.cub (CubeWorld CubeMap)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_schematic: bpy.props.BoolProperty(
        name="*.schematic (Minecraft Schematic)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_dat: bpy.props.BoolProperty(
        name="*.dat (Minecraft level dat)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_mca: bpy.props.BoolProperty(
        name="*.mca (Minecraft Anvil Region)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_mts: bpy.props.BoolProperty(
        name="*.mts (Minetest Template)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxc: bpy.props.BoolProperty(
        name="*.vxc (Sandbox VoxEdit Collection)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxr: bpy.props.BoolProperty(
        name="*.vxr (Sandbox VoxEdit Hierarchy)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxt: bpy.props.BoolProperty(
        name="*.vxt (Sandbox VoxEdit Tilemap)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxm: bpy.props.BoolProperty(
        name="*.vxm (Sandbox VoxEdit Model)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_xraw: bpy.props.BoolProperty(
        name="*.xraw (MagicaVoxel XRAW)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxl: bpy.props.BoolProperty(
        name="*.vxl (Tiberian Sun)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_kv6: bpy.props.BoolProperty(
        name="*.kv6 (Voxlap Voxel Engine)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_kvx: bpy.props.BoolProperty(
        name="*.kvx (Voxlap Voxel model format)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_scn: bpy.props.BoolProperty(
        name="*.scn (Animatoon 3D Scene)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_csv: bpy.props.BoolProperty(
        name="*.csv (Sproxel csv)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_sment: bpy.props.BoolProperty(
        name="*.sment (StarMade)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_gox: bpy.props.BoolProperty(
        name="*.gox (Goxel)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vmax: bpy.props.BoolProperty(
        name="*.vmax (Voxel Max)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vbx: bpy.props.BoolProperty(
        name="*.vbx (Voxel Builder)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_v3a: bpy.props.BoolProperty(
        name="*.v3a (Voxel3D)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vengi: bpy.props.BoolProperty(
        name="*.vengi (Vengi)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_nvm: bpy.props.BoolProperty(
        name="*.nvm (Nicks Voxel Model)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_pcubes: bpy.props.BoolProperty(
        name="*.pcubes (Particubes)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_csm: bpy.props.BoolProperty(
        name="*.csm (CuBic Mesh)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_3zh: bpy.props.BoolProperty(
        name="*.3zh (Cubzh)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_b64: bpy.props.BoolProperty(
        name="*.b64 (Cubzh World)",
        default=True,
        update=update_bool_property,
    ) # type: ignore


    def draw(self, context: bpy_types.Context) -> None:
        layout = self.layout
        layout.label(text="Default Export Formats:")

        layout.prop(self, "type_vox")
        layout.prop(self, "type_qb")
        layout.prop(self, "type_qbt")
        layout.prop(self, "type_qef")
        layout.prop(self, "type_qbcl")
        layout.prop(self, "type_binvox")
        layout.prop(self, "type_cub")
        layout.prop(self, "type_schematic")
        layout.prop(self, "type_dat")
        layout.prop(self, "type_mca")
        layout.prop(self, "type_mts")
        layout.prop(self, "type_vxc")
        layout.prop(self, "type_vxr")
        layout.prop(self, "type_vxt")
        layout.prop(self, "type_vxm")
        layout.prop(self, "type_xraw")
        layout.prop(self, "type_vxl")
        layout.prop(self, "type_kv6")
        layout.prop(self, "type_kvx")
        layout.prop(self, "type_scn")
        layout.prop(self, "type_csv")
        layout.prop(self, "type_sment")
        layout.prop(self, "type_gox")
        layout.prop(self, "type_vmax")
        layout.prop(self, "type_vbx")
        layout.prop(self, "type_v3a")
        layout.prop(self, "type_vengi")
        layout.prop(self, "type_nvm")
        layout.prop(self, "type_pcubes")
        layout.prop(self, "type_csm")
        layout.prop(self, "type_3zh")
        layout.prop(self, "type_b64")