# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-addon-preferences-file.sh
# ============================================================================

import bpy
import bpy_types

from bpy.types import UILayout
from typing import List

from voxelity_pro.ui.voxel_formats_export_menu import VoxelFormatsExportMenu
from voxelity_pro.ui.voxel_formats_export_menu import register as register_vox_export_menu, unregister as unregister_vox_export_menu, get_voxel_exporter_by_type
from voxelity_pro.ui.voxel_formats_import_menu import register as register_vox_import_menu, unregister as unregister_vox_import_menu, get_voxel_importer_by_type
from voxelity_pro.utils.utils import Utils

def update_voxel_formats_preferences() -> None:
    addon: bpy.types.Addon = bpy.context.preferences.addons[VoxelityAddonPreferences.bl_idname]
    prefs: VoxelityAddonPreferences = addon.preferences
    VoxelFormatsExportMenu.PREFERENCES_FORMATS.clear()
    for i, item in enumerate(VoxelFormatsExportMenu.FORMATS):
        if not i or getattr(prefs, f"type_{item[0].lower()}"):
            VoxelFormatsExportMenu.PREFERENCES_FORMATS.append(item)

def update_bool_property(self, _: bpy_types.Context, vox_type: str) -> None:
    exporter = get_voxel_exporter_by_type(vox_type)
    importer = get_voxel_importer_by_type(vox_type)

    if getattr(self, f"type_{vox_type}"):
        if exporter:
            Utils.try_register_operator(exporter)
        if importer:
            Utils.try_register_operator(importer)
    else:
        if exporter:
            Utils.try_unregister_operator(exporter)
        if importer:
            Utils.try_unregister_operator(importer)

    update_voxel_formats_preferences()

class PREFERENCES_OT_CheckVoxelFormatsCheckboxesOperator(bpy.types.Operator):
    bl_idname = "preferences.voxelity_check_voxel_formats_checkboxes"
    bl_label = "Check All"
    bl_description = "Tick all checkboxes"
    bl_options = {'INTERNAL'}

    def execute(self, context) -> set[str]:
        addon_preferences: bpy.types.Addon = context.preferences.addons[VoxelityAddonPreferences.bl_idname]
        preferences: VoxelityAddonPreferences = addon_preferences.preferences
        preferences.check_all_checkboxes()
        return {'FINISHED'}

class PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator(bpy.types.Operator):
    bl_idname = "preferences.voxelity_clear_voxel_formats_checkboxes"
    bl_label = "Uncheck All"
    bl_description = "Untick all checkboxes"
    bl_options = {'INTERNAL'}

    def execute(self, context) -> set[str]:
        addon_preferences: bpy.types.Addon = context.preferences.addons[VoxelityAddonPreferences.bl_idname]
        preferences: VoxelityAddonPreferences = addon_preferences.preferences
        preferences.clear_all_checkboxes()
        bpy.context.scene.voxelity_pro_properties.export_format = VoxelFormatsExportMenu.SELECTION_NONE
        return {'FINISHED'}

class VoxelityAddonPreferences(bpy.types.AddonPreferences):
    bl_idname = Utils.get_addon_module_name() # __name__ if the class is defined inside __init__.py

    type_vox: bpy.props.BoolProperty(
        name="*.vox (MagicaVoxel)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vox")
    ) # type: ignore

    type_qb: bpy.props.BoolProperty(
        name="*.qb (Qubicle Binary Exchange)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "qb")
    ) # type: ignore

    type_qbt: bpy.props.BoolProperty(
        name="*.qbt (Qubicle Binary Tree Exchange)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "qbt")
    ) # type: ignore

    type_qef: bpy.props.BoolProperty(
        name="*.qef (Qubicle Exchange Format ASCII)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "qef")
    ) # type: ignore

    type_qbcl: bpy.props.BoolProperty(
        name="*.qbcl (Qubicle Project)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "qbcl")
    ) # type: ignore

    type_binvox: bpy.props.BoolProperty(
        name="*.binvox (Binvox command line voxelizer)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "binvox")
    ) # type: ignore

    type_cub: bpy.props.BoolProperty(
        name="*.cub (CubeWorld CubeMap)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "cub")
    ) # type: ignore

    type_schematic: bpy.props.BoolProperty(
        name="*.schematic (Minecraft Schematic)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "schematic")
    ) # type: ignore

    type_dat: bpy.props.BoolProperty(
        name="*.dat (Minecraft level dat)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "dat")
    ) # type: ignore

    type_mca: bpy.props.BoolProperty(
        name="*.mca (Minecraft Anvil Region)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "mca")
    ) # type: ignore

    type_mts: bpy.props.BoolProperty(
        name="*.mts (Minetest Template)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "mts")
    ) # type: ignore

    type_vxc: bpy.props.BoolProperty(
        name="*.vxc (Sandbox VoxEdit Collection)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vxc")
    ) # type: ignore

    type_vxr: bpy.props.BoolProperty(
        name="*.vxr (Sandbox VoxEdit Hierarchy)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vxr")
    ) # type: ignore

    type_vxt: bpy.props.BoolProperty(
        name="*.vxt (Sandbox VoxEdit Tilemap)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vxt")
    ) # type: ignore

    type_vxm: bpy.props.BoolProperty(
        name="*.vxm (Sandbox VoxEdit Model)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vxm")
    ) # type: ignore

    type_xraw: bpy.props.BoolProperty(
        name="*.xraw (MagicaVoxel XRAW)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "xraw")
    ) # type: ignore

    type_vxl: bpy.props.BoolProperty(
        name="*.vxl (Tiberian Sun)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vxl")
    ) # type: ignore

    type_kv6: bpy.props.BoolProperty(
        name="*.kv6 (Voxlap Voxel Engine)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "kv6")
    ) # type: ignore

    type_kvx: bpy.props.BoolProperty(
        name="*.kvx (Voxlap Voxel model format)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "kvx")
    ) # type: ignore

    type_scn: bpy.props.BoolProperty(
        name="*.scn (Animatoon 3D Scene)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "scn")
    ) # type: ignore

    type_csv: bpy.props.BoolProperty(
        name="*.csv (Sproxel csv)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "csv")
    ) # type: ignore

    type_sment: bpy.props.BoolProperty(
        name="*.sment (StarMade Blueprint)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "sment")
    ) # type: ignore

    type_gox: bpy.props.BoolProperty(
        name="*.gox (Goxel)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "gox")
    ) # type: ignore

    type_vmax: bpy.props.BoolProperty(
        name="*.vmax (Voxel Max)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vmax")
    ) # type: ignore

    type_vbx: bpy.props.BoolProperty(
        name="*.vbx (Voxel Builder)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vbx")
    ) # type: ignore

    type_v3a: bpy.props.BoolProperty(
        name="*.v3a (Voxel3D)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "v3a")
    ) # type: ignore

    type_vengi: bpy.props.BoolProperty(
        name="*.vengi (Vengi)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "vengi")
    ) # type: ignore

    type_nvm: bpy.props.BoolProperty(
        name="*.nvm (Nicks Voxel Model)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "nvm")
    ) # type: ignore

    type_pcubes: bpy.props.BoolProperty(
        name="*.pcubes (Particubes)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "pcubes")
    ) # type: ignore

    type_csm: bpy.props.BoolProperty(
        name="*.csm (CuBic Mesh)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "csm")
    ) # type: ignore

    type_3zh: bpy.props.BoolProperty(
        name="*.3zh (Cubzh)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "3zh")
    ) # type: ignore

    type_b64: bpy.props.BoolProperty(
        name="*.b64 (Cubzh World)",
        default=True,
        update=lambda self, context: update_bool_property(self, context, "b64")
    ) # type: ignore


    CHECKBOXES: List[str] = ["type_vox","type_qb","type_qbt","type_qef","type_qbcl","type_binvox","type_cub","type_schematic","type_dat","type_mca","type_mts","type_vxc","type_vxr","type_vxt","type_vxm","type_xraw","type_vxl","type_kv6","type_kvx","type_scn","type_csv","type_sment","type_gox","type_vmax","type_vbx","type_v3a","type_vengi","type_nvm","type_pcubes","type_csm","type_3zh","type_b64",]

    def set_checkbox(self, prop_name: str, value: bool) -> None:
        if getattr(self, prop_name) != value:
            setattr(self, prop_name, value)

    def check_all_checkboxes(self) -> None:
        for prop_name in self.CHECKBOXES:
            self.set_checkbox(prop_name, True)

    def clear_all_checkboxes(self) -> None:
        for prop_name in self.CHECKBOXES:
            self.set_checkbox(prop_name, False)

    def draw(self, _: bpy_types.Context) -> None:
        layout: UILayout = self.layout
        options_box: UILayout = layout.box()
        box: UILayout = options_box.box()

        split: UILayout = box.split(factor=0.5)
        col1: UILayout = split.column()
        col1.operator(PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator.bl_idname, text="Uncheck All Boxes")
        col2 = split.column()
        col2.operator(PREFERENCES_OT_CheckVoxelFormatsCheckboxesOperator.bl_idname, text="Check All Boxes")

        box = options_box.box()
        split = box.split(factor=0.33)
        col1 = split.column()
        col2 = split.column()
        col3 = split.column()

        num_boxes = len(self.CHECKBOXES)
        boxes_per_column = num_boxes // 3
        extra_boxes = num_boxes % 3

        columns = [col1, col2, col3]
        checkbox_index = 0
        for i in range(3):
            num_boxes_in_column = boxes_per_column + (1 if i < extra_boxes else 0)
            for j in range(num_boxes_in_column):
                columns[i].prop(self, self.CHECKBOXES[checkbox_index])
                checkbox_index += 1

        box = layout.box()
        box.label(text=f"This addon is powered by vengi-voxconvert v{Utils.get_voxconvert_version()} by {Utils.get_voxconvert_author()}")

def register() -> None:
    bpy.utils.register_class(VoxelityAddonPreferences)
    bpy.utils.register_class(PREFERENCES_OT_CheckVoxelFormatsCheckboxesOperator)
    bpy.utils.register_class(PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator)
    enabled_vox_types: List[str] = Utils.get_preferences_voxel_types()
    register_vox_export_menu(enabled_vox_types)
    register_vox_import_menu(enabled_vox_types)
    update_voxel_formats_preferences()

def unregister() -> None:
    bpy.utils.unregister_class(VoxelityAddonPreferences)
    bpy.utils.unregister_class(PREFERENCES_OT_CheckVoxelFormatsCheckboxesOperator)
    bpy.utils.unregister_class(PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator)
    unregister_vox_export_menu()
    unregister_vox_import_menu()