# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-addon-preferences-file.sh
# ============================================================================

import bpy
import bpy_types

from bpy.types import UILayout
from typing import List

from voxility_pro.ui.voxel_formats_export_menu import register as register_vox_export_menu, unregister as unregister_vox_export_menu
from voxility_pro.ui.voxel_formats_import_menu import register as register_vox_import_menu, unregister as unregister_vox_import_menu

def update_bool_property(self, context: bpy_types.Context) -> None:

    if self.type_vox:
        pass
    if self.type_qb:
        pass
    if self.type_qbt:
        pass
    if self.type_qef:
        pass
    if self.type_qbcl:
        pass
    if self.type_binvox:
        pass
    if self.type_cub:
        pass
    if self.type_schematic:
        pass
    if self.type_dat:
        pass
    if self.type_mca:
        pass
    if self.type_mts:
        pass
    if self.type_vxc:
        pass
    if self.type_vxr:
        pass
    if self.type_vxt:
        pass
    if self.type_vxm:
        pass
    if self.type_xraw:
        pass
    if self.type_vxl:
        pass
    if self.type_kv6:
        pass
    if self.type_kvx:
        pass
    if self.type_scn:
        pass
    if self.type_csv:
        pass
    if self.type_sment:
        pass
    if self.type_gox:
        pass
    if self.type_vmax:
        pass
    if self.type_vbx:
        pass
    if self.type_v3a:
        pass
    if self.type_vengi:
        pass
    if self.type_nvm:
        pass
    if self.type_pcubes:
        pass
    if self.type_csm:
        pass
    if self.type_3zh:
        pass
    if self.type_b64:
        pass

class PREFERENCES_OT_UpdateVoxelFormatsOperator(bpy.types.Operator):
    bl_idname = "preferences.voxility_update_voxel_formats"
    bl_label = "Update Voxel Formats"
    bl_description = "Update voxel formats to only show preferred types"
    bl_options = {'INTERNAL'}

    def execute(self, context) -> set[str]:
        self.report({'INFO'}, "Voxel update formats ... TODO")
        return {'FINISHED'}

class PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator(bpy.types.Operator):
    bl_idname = "preferences.voxility_clear_voxel_formats_checkboxes"
    bl_label = "Uncheck All"
    bl_description = "Uncheck all checkboxes"
    bl_options = {'INTERNAL'}

    def execute(self, context) -> set[str]:
        addon_preferences: bpy.types.Addon = context.preferences.addons[AddonPreferences.bl_idname]
        preferences: AddonPreferences = addon_preferences.preferences
        preferences.clear_all_checkboxes()
        return {'FINISHED'}

class AddonPreferences(bpy.types.AddonPreferences):
    bl_idname = "voxility_pro" # __name__ if the class is defined inside __init__.py

    type_vox: bpy.props.BoolProperty(
        name="*.vox (MagicaVoxel)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qb: bpy.props.BoolProperty(
        name="*.qb (Qubicle Binary Exchange)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qbt: bpy.props.BoolProperty(
        name="*.qbt (Qubicle Binary Tree Exchange)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qef: bpy.props.BoolProperty(
        name="*.qef (Qubicle Exchange Format ASCII)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_qbcl: bpy.props.BoolProperty(
        name="*.qbcl (Qubicle Project)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_binvox: bpy.props.BoolProperty(
        name="*.binvox (Binvox command line voxelizer)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_cub: bpy.props.BoolProperty(
        name="*.cub (CubeWorld CubeMap)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_schematic: bpy.props.BoolProperty(
        name="*.schematic (Minecraft Schematic)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_dat: bpy.props.BoolProperty(
        name="*.dat (Minecraft level dat)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_mca: bpy.props.BoolProperty(
        name="*.mca (Minecraft Anvil Region)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_mts: bpy.props.BoolProperty(
        name="*.mts (Minetest Template)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxc: bpy.props.BoolProperty(
        name="*.vxc (Sandbox VoxEdit Collection)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxr: bpy.props.BoolProperty(
        name="*.vxr (Sandbox VoxEdit Hierarchy)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxt: bpy.props.BoolProperty(
        name="*.vxt (Sandbox VoxEdit Tilemap)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxm: bpy.props.BoolProperty(
        name="*.vxm (Sandbox VoxEdit Model)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_xraw: bpy.props.BoolProperty(
        name="*.xraw (MagicaVoxel XRAW)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vxl: bpy.props.BoolProperty(
        name="*.vxl (Tiberian Sun)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_kv6: bpy.props.BoolProperty(
        name="*.kv6 (Voxlap Voxel Engine)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_kvx: bpy.props.BoolProperty(
        name="*.kvx (Voxlap Voxel model format)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_scn: bpy.props.BoolProperty(
        name="*.scn (Animatoon 3D Scene)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_csv: bpy.props.BoolProperty(
        name="*.csv (Sproxel csv)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_sment: bpy.props.BoolProperty(
        name="*.sment (StarMade)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_gox: bpy.props.BoolProperty(
        name="*.gox (Goxel)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vmax: bpy.props.BoolProperty(
        name="*.vmax (Voxel Max)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vbx: bpy.props.BoolProperty(
        name="*.vbx (Voxel Builder)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_v3a: bpy.props.BoolProperty(
        name="*.v3a (Voxel3D)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_vengi: bpy.props.BoolProperty(
        name="*.vengi (Vengi)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_nvm: bpy.props.BoolProperty(
        name="*.nvm (Nicks Voxel Model)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_pcubes: bpy.props.BoolProperty(
        name="*.pcubes (Particubes)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_csm: bpy.props.BoolProperty(
        name="*.csm (CuBic Mesh)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_3zh: bpy.props.BoolProperty(
        name="*.3zh (Cubzh)",
        default=True,
        update=update_bool_property,
    ) # type: ignore

    type_b64: bpy.props.BoolProperty(
        name="*.b64 (Cubzh World)",
        default=True,
        update=update_bool_property,
    ) # type: ignore


    CHECKBOXES: List[str] = ["type_vox","type_qb","type_qbt","type_qef","type_qbcl","type_binvox","type_cub","type_schematic","type_dat","type_mca","type_mts","type_vxc","type_vxr","type_vxt","type_vxm","type_xraw","type_vxl","type_kv6","type_kvx","type_scn","type_csv","type_sment","type_gox","type_vmax","type_vbx","type_v3a","type_vengi","type_nvm","type_pcubes","type_csm","type_3zh","type_b64",]

    def set_checkbox(self, prop_name: str, value: bool) -> None:
        setattr(self, prop_name, value)

    def clear_all_checkboxes(self) -> None:
        for prop_name in self.CHECKBOXES:
            self.set_checkbox(prop_name, False)

    def draw(self, context: bpy_types.Context) -> None:
        layout: UILayout = self.layout
        box: UILayout = layout.box()

        split: UILayout = box.split(factor=0.3)
        col: UILayout = split.column()
        col.operator(PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator.bl_idname, text="Uncheck All")
        col = split.column()
        col.alert = True
        col.operator(PREFERENCES_OT_UpdateVoxelFormatsOperator.bl_idname, text="Update Voxel Formats")

        layout.label(text="Tick your voxel formats and then click Update Voxel Formats")
        box = layout.box()

        for prop_name in self.CHECKBOXES:
            box.prop(self, prop_name)

def get_enabled_voxel_types() -> List[str]:
    addon: bpy.types.Addon = bpy.context.preferences.addons[AddonPreferences.bl_idname]
    addon_prefs: AddonPreferences = addon.preferences
    types: List[str] = []
    for prop_name in AddonPreferences.CHECKBOXES:
        if getattr(addon_prefs, prop_name):
            types.append(prop_name.split("_")[1])
    return types

def register() -> None:
    bpy.utils.register_class(AddonPreferences)
    bpy.utils.register_class(PREFERENCES_OT_UpdateVoxelFormatsOperator)
    bpy.utils.register_class(PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator)
    enabled_vox_types: List[str] = get_enabled_voxel_types()
    register_vox_export_menu(enabled_vox_types)
    register_vox_import_menu(enabled_vox_types)

def unregister() -> None:
    bpy.utils.unregister_class(AddonPreferences)
    bpy.utils.unregister_class(PREFERENCES_OT_UpdateVoxelFormatsOperator)
    bpy.utils.unregister_class(PREFERENCES_OT_ClearVoxelFormatsCheckboxesOperator)
    unregister_vox_export_menu()
    unregister_vox_import_menu()