# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-vox-menu-py-file.sh
# ============================================================================

import bpy
import bpy_types

from typing import List, Tuple

from voxility_pro.operators.voxel.operator_voxconvert import OperatorVoxconvert

from voxility_pro.operators.voxel.exporters.operator_vox_exporter import EXPORT_OT_magicavoxel
from voxility_pro.operators.voxel.exporters.operator_qb_exporter import EXPORT_OT_qubicle_binary_exchange
from voxility_pro.operators.voxel.exporters.operator_qbt_exporter import EXPORT_OT_qubicle_binary_tree_exchange
from voxility_pro.operators.voxel.exporters.operator_qef_exporter import EXPORT_OT_qubicle_exchange_format_ascii
from voxility_pro.operators.voxel.exporters.operator_qbcl_exporter import EXPORT_OT_qubicle_project
from voxility_pro.operators.voxel.exporters.operator_binvox_exporter import EXPORT_OT_binvox_command_line_voxelizer
from voxility_pro.operators.voxel.exporters.operator_cub_exporter import EXPORT_OT_cubeworld_cubemap
from voxility_pro.operators.voxel.exporters.operator_schematic_exporter import EXPORT_OT_minecraft_schematic
from voxility_pro.operators.voxel.exporters.operator_dat_exporter import EXPORT_OT_minecraft_level_dat
from voxility_pro.operators.voxel.exporters.operator_mca_exporter import EXPORT_OT_minecraft_anvil_region
from voxility_pro.operators.voxel.exporters.operator_mts_exporter import EXPORT_OT_minetest_template
from voxility_pro.operators.voxel.exporters.operator_vxc_exporter import EXPORT_OT_sandbox_voxedit_collection
from voxility_pro.operators.voxel.exporters.operator_vxr_exporter import EXPORT_OT_sandbox_voxedit_hierarchy
from voxility_pro.operators.voxel.exporters.operator_vxt_exporter import EXPORT_OT_sandbox_voxedit_tilemap
from voxility_pro.operators.voxel.exporters.operator_vxm_exporter import EXPORT_OT_sandbox_voxedit_model
from voxility_pro.operators.voxel.exporters.operator_xraw_exporter import EXPORT_OT_magicavoxel_xraw
from voxility_pro.operators.voxel.exporters.operator_vxl_exporter import EXPORT_OT_tiberian_sun
from voxility_pro.operators.voxel.exporters.operator_kv6_exporter import EXPORT_OT_voxlap_voxel_engine
from voxility_pro.operators.voxel.exporters.operator_kvx_exporter import EXPORT_OT_voxlap_voxel_model_format
from voxility_pro.operators.voxel.exporters.operator_scn_exporter import EXPORT_OT_animatoon_3d_scene
from voxility_pro.operators.voxel.exporters.operator_csv_exporter import EXPORT_OT_sproxel_csv
from voxility_pro.operators.voxel.exporters.operator_sment_exporter import EXPORT_OT_starmade
from voxility_pro.operators.voxel.exporters.operator_gox_exporter import EXPORT_OT_goxel
from voxility_pro.operators.voxel.exporters.operator_vmax_exporter import EXPORT_OT_voxel_max
from voxility_pro.operators.voxel.exporters.operator_vbx_exporter import EXPORT_OT_voxel_builder
from voxility_pro.operators.voxel.exporters.operator_v3a_exporter import EXPORT_OT_voxel3d
from voxility_pro.operators.voxel.exporters.operator_vengi_exporter import EXPORT_OT_vengi
from voxility_pro.operators.voxel.exporters.operator_nvm_exporter import EXPORT_OT_nicks_voxel_model
from voxility_pro.operators.voxel.exporters.operator_pcubes_exporter import EXPORT_OT_particubes
from voxility_pro.operators.voxel.exporters.operator_csm_exporter import EXPORT_OT_cubic_mesh
from voxility_pro.operators.voxel.exporters.operator_3zh_exporter import EXPORT_OT_cubzh
from voxility_pro.operators.voxel.exporters.operator_b64_exporter import EXPORT_OT_cubzh_world


CLASSES: List[OperatorVoxconvert] = [
    EXPORT_OT_magicavoxel,
    EXPORT_OT_qubicle_binary_exchange,
    EXPORT_OT_qubicle_binary_tree_exchange,
    EXPORT_OT_qubicle_exchange_format_ascii,
    EXPORT_OT_qubicle_project,
    EXPORT_OT_binvox_command_line_voxelizer,
    EXPORT_OT_cubeworld_cubemap,
    EXPORT_OT_sandbox_voxedit_hierarchy,
    EXPORT_OT_sandbox_voxedit_model,
    EXPORT_OT_magicavoxel_xraw,
    EXPORT_OT_tiberian_sun,
    EXPORT_OT_voxlap_voxel_engine,
    EXPORT_OT_voxlap_voxel_model_format,
    EXPORT_OT_goxel,
    EXPORT_OT_voxel_max,
    EXPORT_OT_voxel3d,
    EXPORT_OT_vengi,
    EXPORT_OT_cubzh,
]

class VoxelFormatsExportMenu(bpy.types.Menu):
    bl_idname = "TOPBAR_MT_select_VoxelFormatsExportMenu_submenu"
    bl_label = "Select"

    FORMATS: List[Tuple[str, str, str]] = [
        ("NONE", "None", "No specific target format. Only voxelize within this application."),
        ("VOX", "vox (MagicaVoxel)", "Target format: *.vox"),
        ("QB", "qb (Qubicle Binary Exchange)", "Target format: *.qb"),
        ("QBT", "qbt (Qubicle Binary Tree Exchange)", "Target format: *.qbt"),
        ("QEF", "qef (Qubicle Exchange Format ASCII)", "Target format: *.qef"),
        ("QBCL", "qbcl (Qubicle Project)", "Target format: *.qbcl"),
        ("BINVOX", "binvox (Binvox command line voxelizer)", "Target format: *.binvox"),
        ("CUB", "cub (CubeWorld CubeMap)", "Target format: *.cub"),
        ("VXR", "vxr (Sandbox VoxEdit Hierarchy)", "Target format: *.vxr"),
        ("VXM", "vxm (Sandbox VoxEdit Model)", "Target format: *.vxm"),
        ("XRAW", "xraw (MagicaVoxel XRAW)", "Target format: *.xraw"),
        ("VXL", "vxl (Tiberian Sun)", "Target format: *.vxl"),
        ("KV6", "kv6 (Voxlap Voxel Engine)", "Target format: *.kv6"),
        ("KVX", "kvx (Voxlap Voxel model format)", "Target format: *.kvx"),
        ("GOX", "gox (Goxel)", "Target format: *.gox"),
        ("VMAX", "vmax (Voxel Max)", "Target format: *.vmax"),
        ("V3A", "v3a (Voxel3D)", "Target format: *.v3a"),
        ("VENGI", "vengi (Vengi)", "Target format: *.vengi"),
        ("3ZH", "3zh (Cubzh)", "Target format: *.3zh"),
    ]

    @staticmethod
    def get_formats_list_value(index: int=0) -> str:
        return VoxelFormatsExportMenu.FORMATS[index][0]

    def draw(self, _context: bpy_types.Context) -> None:
        layout: bpy.types.UILayout = self.layout
        for cls in CLASSES:
            layout.operator(cls.bl_idname, text=cls.bl_label)

def menu_vox_export_func_callback(self, _context: bpy_types.Context) -> None:
    self.layout.operator(EXPORT_OT_magicavoxel.bl_idname)

def menu_VoxelFormatsExportMenu_func_callback(self, _context: bpy_types.Context) -> None:
    self.layout.menu(VoxelFormatsExportMenu.bl_idname, text="Voxility Voxel Formats")

def register() -> None:
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    bpy.utils.register_class(VoxelFormatsExportMenu)
    bpy.types.TOPBAR_MT_file_export.append(menu_vox_export_func_callback)
    bpy.types.TOPBAR_MT_file_export.append(menu_VoxelFormatsExportMenu_func_callback)

def unregister() -> None:
    for cls in CLASSES:
        bpy.utils.unregister_class(cls)
    bpy.utils.unregister_class(VoxelFormatsExportMenu)
    bpy.types.TOPBAR_MT_file_export.remove(menu_vox_export_func_callback)
    bpy.types.TOPBAR_MT_file_export.remove(menu_VoxelFormatsExportMenu_func_callback)