# ============================================================================
# Author: Harry McKenzie
# This file was autogenerated and should not be edited manually.
# Generated by script ./scripts/generate-vox-menu-py-file.sh
# ============================================================================

import bpy
import re

from typing import List, Tuple

from voxelity_pro.operators.voxel.operator_voxconvert import OperatorVoxconvert
from voxelity_pro.exceptions.unknown_voxel_type_error import UnknownVoxelTypeError
from voxelity_pro.utils.utils import Utils

from voxelity_pro.operators.voxel.importers.operator_vox_importer import IMPORT_OT_magicavoxel
from voxelity_pro.operators.voxel.importers.operator_qb_importer import IMPORT_OT_qubicle_binary_exchange
from voxelity_pro.operators.voxel.importers.operator_qbt_importer import IMPORT_OT_qubicle_binary_tree_exchange
from voxelity_pro.operators.voxel.importers.operator_qef_importer import IMPORT_OT_qubicle_exchange_format_ascii
from voxelity_pro.operators.voxel.importers.operator_qbcl_importer import IMPORT_OT_qubicle_project
from voxelity_pro.operators.voxel.importers.operator_binvox_importer import IMPORT_OT_binvox_command_line_voxelizer
from voxelity_pro.operators.voxel.importers.operator_cub_importer import IMPORT_OT_cubeworld_cubemap
from voxelity_pro.operators.voxel.importers.operator_schematic_importer import IMPORT_OT_minecraft_schematic
from voxelity_pro.operators.voxel.importers.operator_dat_importer import IMPORT_OT_minecraft_level_dat
from voxelity_pro.operators.voxel.importers.operator_mca_importer import IMPORT_OT_minecraft_anvil_region
from voxelity_pro.operators.voxel.importers.operator_mts_importer import IMPORT_OT_minetest_template
from voxelity_pro.operators.voxel.importers.operator_vxc_importer import IMPORT_OT_sandbox_voxedit_collection
from voxelity_pro.operators.voxel.importers.operator_vxr_importer import IMPORT_OT_sandbox_voxedit_hierarchy
from voxelity_pro.operators.voxel.importers.operator_vxt_importer import IMPORT_OT_sandbox_voxedit_tilemap
from voxelity_pro.operators.voxel.importers.operator_vxm_importer import IMPORT_OT_sandbox_voxedit_model
from voxelity_pro.operators.voxel.importers.operator_xraw_importer import IMPORT_OT_magicavoxel_xraw
from voxelity_pro.operators.voxel.importers.operator_vxl_importer import IMPORT_OT_tiberian_sun
from voxelity_pro.operators.voxel.importers.operator_kv6_importer import IMPORT_OT_voxlap_voxel_engine
from voxelity_pro.operators.voxel.importers.operator_kvx_importer import IMPORT_OT_voxlap_voxel_model_format
from voxelity_pro.operators.voxel.importers.operator_scn_importer import IMPORT_OT_animatoon_3d_scene
from voxelity_pro.operators.voxel.importers.operator_csv_importer import IMPORT_OT_sproxel_csv
from voxelity_pro.operators.voxel.importers.operator_sment_importer import IMPORT_OT_starmade_blueprint
from voxelity_pro.operators.voxel.importers.operator_smtpl_importer import IMPORT_OT_starmade_template
from voxelity_pro.operators.voxel.importers.operator_gox_importer import IMPORT_OT_goxel
from voxelity_pro.operators.voxel.importers.operator_vmax_importer import IMPORT_OT_voxel_max
from voxelity_pro.operators.voxel.importers.operator_vbx_importer import IMPORT_OT_voxel_builder
from voxelity_pro.operators.voxel.importers.operator_v3a_importer import IMPORT_OT_voxel3d
from voxelity_pro.operators.voxel.importers.operator_vengi_importer import IMPORT_OT_vengi
from voxelity_pro.operators.voxel.importers.operator_nvm_importer import IMPORT_OT_nicks_voxel_model
from voxelity_pro.operators.voxel.importers.operator_pcubes_importer import IMPORT_OT_particubes
from voxelity_pro.operators.voxel.importers.operator_csm_importer import IMPORT_OT_cubic_mesh
from voxelity_pro.operators.voxel.importers.operator_3zh_importer import IMPORT_OT_cubzh
from voxelity_pro.operators.voxel.importers.operator_b64_importer import IMPORT_OT_cubzh_world


CLASSES: List[OperatorVoxconvert] = [
    IMPORT_OT_magicavoxel,
    IMPORT_OT_qubicle_binary_exchange,
    IMPORT_OT_qubicle_binary_tree_exchange,
    IMPORT_OT_qubicle_exchange_format_ascii,
    IMPORT_OT_qubicle_project,
    IMPORT_OT_binvox_command_line_voxelizer,
    IMPORT_OT_cubeworld_cubemap,
    IMPORT_OT_minecraft_schematic,
    IMPORT_OT_minecraft_level_dat,
    IMPORT_OT_minecraft_anvil_region,
    IMPORT_OT_minetest_template,
    IMPORT_OT_sandbox_voxedit_collection,
    IMPORT_OT_sandbox_voxedit_hierarchy,
    IMPORT_OT_sandbox_voxedit_tilemap,
    IMPORT_OT_sandbox_voxedit_model,
    IMPORT_OT_magicavoxel_xraw,
    IMPORT_OT_tiberian_sun,
    IMPORT_OT_voxlap_voxel_engine,
    IMPORT_OT_voxlap_voxel_model_format,
    IMPORT_OT_animatoon_3d_scene,
    IMPORT_OT_sproxel_csv,
    IMPORT_OT_starmade_blueprint,
    IMPORT_OT_goxel,
    IMPORT_OT_voxel_max,
    IMPORT_OT_voxel_builder,
    IMPORT_OT_voxel3d,
    IMPORT_OT_vengi,
    IMPORT_OT_nicks_voxel_model,
    IMPORT_OT_particubes,
    IMPORT_OT_cubic_mesh,
    IMPORT_OT_cubzh,
    IMPORT_OT_cubzh_world,
]

class VoxelFormatsImportMenu(bpy.types.Menu):
    bl_idname = "TOPBAR_MT_select_VoxelFormatsImportMenu_submenu"
    bl_label = "Select"

    FORMATS: List[Tuple[str, str, str]] = [
        ("NONE", "None", "No specific target format. Only voxelize within this application."),
        ("VOX", "vox (MagicaVoxel)", "Target format: *.vox"),
        ("QB", "qb (Qubicle Binary Exchange)", "Target format: *.qb"),
        ("QBT", "qbt (Qubicle Binary Tree Exchange)", "Target format: *.qbt"),
        ("QEF", "qef (Qubicle Exchange Format ASCII)", "Target format: *.qef"),
        ("QBCL", "qbcl (Qubicle Project)", "Target format: *.qbcl"),
        ("BINVOX", "binvox (Binvox command line voxelizer)", "Target format: *.binvox"),
        ("CUB", "cub (CubeWorld CubeMap)", "Target format: *.cub"),
        ("SCHEMATIC", "schematic (Minecraft Schematic)", "Target format: *.schematic"),
        ("DAT", "dat (Minecraft level dat)", "Target format: *.dat"),
        ("MCA", "mca (Minecraft Anvil Region)", "Target format: *.mca"),
        ("MTS", "mts (Minetest Template)", "Target format: *.mts"),
        ("VXC", "vxc (Sandbox VoxEdit Collection)", "Target format: *.vxc"),
        ("VXR", "vxr (Sandbox VoxEdit Hierarchy)", "Target format: *.vxr"),
        ("VXT", "vxt (Sandbox VoxEdit Tilemap)", "Target format: *.vxt"),
        ("VXM", "vxm (Sandbox VoxEdit Model)", "Target format: *.vxm"),
        ("XRAW", "xraw (MagicaVoxel XRAW)", "Target format: *.xraw"),
        ("VXL", "vxl (Tiberian Sun)", "Target format: *.vxl"),
        ("KV6", "kv6 (Voxlap Voxel Engine)", "Target format: *.kv6"),
        ("KVX", "kvx (Voxlap Voxel model format)", "Target format: *.kvx"),
        ("SCN", "scn (Animatoon 3D Scene)", "Target format: *.scn"),
        ("CSV", "csv (Sproxel csv)", "Target format: *.csv"),
        ("SMENT", "sment (StarMade Blueprint)", "Target format: *.sment"),
        ("GOX", "gox (Goxel)", "Target format: *.gox"),
        ("VMAX", "vmax (Voxel Max)", "Target format: *.vmax"),
        ("VBX", "vbx (Voxel Builder)", "Target format: *.vbx"),
        ("V3A", "v3a (Voxel3D)", "Target format: *.v3a"),
        ("VENGI", "vengi (Vengi)", "Target format: *.vengi"),
        ("NVM", "nvm (Nicks Voxel Model)", "Target format: *.nvm"),
        ("PCUBES", "pcubes (Particubes)", "Target format: *.pcubes"),
        ("CSM", "csm (CuBic Mesh)", "Target format: *.csm"),
        ("3ZH", "3zh (Cubzh)", "Target format: *.3zh"),
        ("B64", "b64 (Cubzh World)", "Target format: *.b64"),
    ]

    PREFERENCES_FORMATS: List[Tuple[str, str, str]] = [
        ("NONE", "None", "No specific target format. Only voxelize within this application."),
    ] # list is populated by AddonPreferences

    SELECTION_NONE:str = FORMATS[0][0]

    @staticmethod
    def get_format_name(type, camel_notation=False):
        for tuple in VoxelFormatsImportMenu.FORMATS:
            if type != tuple[0]:
                continue
            name = re.search(r"\((.*?)\)", tuple[1]).group(1)
            return name.replace(" ", "_").lower() if camel_notation else name
        return None

    def draw(self, _context: bpy.types.Context) -> None:
        layout: bpy.types.UILayout = self.layout
        for cls in CLASSES:
            if Utils.is_class_registered(cls):
                layout.operator(cls.bl_idname, text=f"{cls.voxel_name} ({cls.filename_ext})")

def menu_vox_import_func_callback(self, _context: bpy.types.Context) -> None:
    self.layout.operator(IMPORT_OT_magicavoxel.bl_idname)

def menu_VoxelFormatsImportMenu_func_callback(self, _context: bpy.types.Context) -> None:
    self.layout.menu(VoxelFormatsImportMenu.bl_idname, text="Voxelity Voxel Formats")

def get_voxel_importer_by_type(voxel_type: str) -> OperatorVoxconvert:
    for cls in CLASSES:
        if voxel_type == cls.voxel_type:
            return cls
    return None

def register(enabled_types: List[str]) -> None:
    for cls in CLASSES:
        if any(type == cls.voxel_type for type in enabled_types):
            Utils.try_register_operator(cls)
    bpy.utils.register_class(VoxelFormatsImportMenu)
    #bpy.types.TOPBAR_MT_file_import.append(menu_vox_import_func_callback)
    bpy.types.TOPBAR_MT_file_import.append(menu_VoxelFormatsImportMenu_func_callback)

def unregister() -> None:
    for cls in CLASSES:
        Utils.try_unregister_operator(cls)
    bpy.utils.unregister_class(VoxelFormatsImportMenu)
    #bpy.types.TOPBAR_MT_file_import.remove(menu_vox_import_func_callback)
    bpy.types.TOPBAR_MT_file_import.remove(menu_VoxelFormatsImportMenu_func_callback)